// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wcgamelive.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - WcgameliveRoot

@interface WcgameliveRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - WatchLive

typedef GPB_ENUM(WatchLive_FieldNumber) {
  WatchLive_FieldNumber_MatchesArray = 1,
};

// apple watch 比分直播接口
@interface WatchLive : GPBMessage

// 赛事列表
// |matchesArray| contains |WatchLive_MatchItem|
@property(nonatomic, readwrite, strong) NSMutableArray *matchesArray;

@end

#pragma mark - WatchLive_MatchItem

typedef GPB_ENUM(WatchLive_MatchItem_FieldNumber) {
  WatchLive_MatchItem_FieldNumber_HomeName = 1,
  WatchLive_MatchItem_FieldNumber_AwayName = 2,
  WatchLive_MatchItem_FieldNumber_HomeLogo = 3,
  WatchLive_MatchItem_FieldNumber_AwayLogo = 4,
  WatchLive_MatchItem_FieldNumber_HomeScore = 5,
  WatchLive_MatchItem_FieldNumber_AwayScore = 6,
  WatchLive_MatchItem_FieldNumber_StartTime = 7,
  WatchLive_MatchItem_FieldNumber_HalfTime = 8,
  WatchLive_MatchItem_FieldNumber_MatchState = 9,
  WatchLive_MatchItem_FieldNumber_OnTime = 10,
};

@interface WatchLive_MatchItem : GPBMessage

// 主队名
@property(nonatomic, readwrite) BOOL hasHomeName;
@property(nonatomic, readwrite, copy) NSString *homeName;

// 客队名
@property(nonatomic, readwrite) BOOL hasAwayName;
@property(nonatomic, readwrite, copy) NSString *awayName;

// 主队图标
@property(nonatomic, readwrite) BOOL hasHomeLogo;
@property(nonatomic, readwrite, copy) NSString *homeLogo;

// 客队图标
@property(nonatomic, readwrite) BOOL hasAwayLogo;
@property(nonatomic, readwrite, copy) NSString *awayLogo;

// 主队得分
@property(nonatomic, readwrite) BOOL hasHomeScore;
@property(nonatomic, readwrite) int32_t homeScore;

// 客队得分
@property(nonatomic, readwrite) BOOL hasAwayScore;
@property(nonatomic, readwrite) int32_t awayScore;

// 开赛时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

// 半场开始时间
@property(nonatomic, readwrite) BOOL hasHalfTime;
@property(nonatomic, readwrite, copy) NSString *halfTime;

// 比赛状态
@property(nonatomic, readwrite) BOOL hasMatchState;
@property(nonatomic, readwrite) int32_t matchState;

// 比赛进行时间
@property(nonatomic, readwrite) BOOL hasOnTime;
@property(nonatomic, readwrite, copy) NSString *onTime;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
