// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chase_center.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "ChaseCenter.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PBMChaseCenterRoot

@implementation PBMChaseCenterRoot

@end

static GPBFileDescriptor *PBMChaseCenterRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"Dacai.Protobuf"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBMChaseCenterItem

@implementation PBMChaseCenterItem

@dynamic hasChaseId, chaseId;
@dynamic hasGameType, gameType;
@dynamic hasStartTime, startTime;
@dynamic hasTotalIssueCount, totalIssueCount;
@dynamic hasChasedIssueCount, chasedIssueCount;

typedef struct PBMChaseCenterItem_Storage {
  uint32_t _has_storage_[1];
  int32_t gameType;
  int32_t totalIssueCount;
  int32_t chasedIssueCount;
  NSString *startTime;
  int64_t chaseId;
} PBMChaseCenterItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "chaseId",
        .number = PBMChaseCenterItem_FieldNumber_ChaseId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterItem_Storage, chaseId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameType",
        .number = PBMChaseCenterItem_FieldNumber_GameType,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterItem_Storage, gameType),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "startTime",
        .number = PBMChaseCenterItem_FieldNumber_StartTime,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterItem_Storage, startTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "totalIssueCount",
        .number = PBMChaseCenterItem_FieldNumber_TotalIssueCount,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterItem_Storage, totalIssueCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chasedIssueCount",
        .number = PBMChaseCenterItem_FieldNumber_ChasedIssueCount,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterItem_Storage, chasedIssueCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMChaseCenterItem class]
                                              rootClass:[PBMChaseCenterRoot class]
                                                   file:PBMChaseCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMChaseCenterItem_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMChaseCenterList

@implementation PBMChaseCenterList

@dynamic chaseCenterItemsArray;
@dynamic hasTotalItemCount, totalItemCount;

typedef struct PBMChaseCenterList_Storage {
  uint32_t _has_storage_[1];
  int32_t totalItemCount;
  NSMutableArray *chaseCenterItemsArray;
} PBMChaseCenterList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "chaseCenterItemsArray",
        .number = PBMChaseCenterList_FieldNumber_ChaseCenterItemsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMChaseCenterList_Storage, chaseCenterItemsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMChaseCenterItem),
        .fieldOptions = NULL,
      },
      {
        .name = "totalItemCount",
        .number = PBMChaseCenterList_FieldNumber_TotalItemCount,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterList_Storage, totalItemCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMChaseCenterList class]
                                              rootClass:[PBMChaseCenterRoot class]
                                                   file:PBMChaseCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMChaseCenterList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMChaseCenterInfo

@implementation PBMChaseCenterInfo

@dynamic hasStartTime, startTime;
@dynamic hasTotalIssueCount, totalIssueCount;
@dynamic hasChasedIssueCount, chasedIssueCount;
@dynamic hasChaseTotalMoney, chaseTotalMoney;
@dynamic hasChasedMoney, chasedMoney;
@dynamic hasChasedState, chasedState;
@dynamic hasQuantity, quantity;
@dynamic hasMultiple, multiple;
@dynamic hasBetContent, betContent;
@dynamic chaseInfoArray;
@dynamic hasPayStatus, payStatus;
@dynamic hasGameType, gameType;
@dynamic hasStartGameName, startGameName;
@dynamic hasStartGameId, startGameId;

typedef struct PBMChaseCenterInfo_Storage {
  uint32_t _has_storage_[1];
  int32_t totalIssueCount;
  int32_t chasedIssueCount;
  int32_t chasedState;
  int32_t payStatus;
  int32_t gameType;
  NSString *startTime;
  NSString *betContent;
  NSMutableArray *chaseInfoArray;
  NSString *startGameName;
  int64_t chaseTotalMoney;
  int64_t chasedMoney;
  int64_t quantity;
  int64_t multiple;
  int64_t startGameId;
} PBMChaseCenterInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "startTime",
        .number = PBMChaseCenterInfo_FieldNumber_StartTime,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_Storage, startTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "totalIssueCount",
        .number = PBMChaseCenterInfo_FieldNumber_TotalIssueCount,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterInfo_Storage, totalIssueCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chasedIssueCount",
        .number = PBMChaseCenterInfo_FieldNumber_ChasedIssueCount,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterInfo_Storage, chasedIssueCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chaseTotalMoney",
        .number = PBMChaseCenterInfo_FieldNumber_ChaseTotalMoney,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_Storage, chaseTotalMoney),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chasedMoney",
        .number = PBMChaseCenterInfo_FieldNumber_ChasedMoney,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_Storage, chasedMoney),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chasedState",
        .number = PBMChaseCenterInfo_FieldNumber_ChasedState,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterInfo_Storage, chasedState),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "quantity",
        .number = PBMChaseCenterInfo_FieldNumber_Quantity,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_Storage, quantity),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "multiple",
        .number = PBMChaseCenterInfo_FieldNumber_Multiple,
        .hasIndex = 7,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_Storage, multiple),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "betContent",
        .number = PBMChaseCenterInfo_FieldNumber_BetContent,
        .hasIndex = 8,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_Storage, betContent),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chaseInfoArray",
        .number = PBMChaseCenterInfo_FieldNumber_ChaseInfoArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMChaseCenterInfo_Storage, chaseInfoArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMChaseCenterInfo_ChaseCenterItem),
        .fieldOptions = NULL,
      },
      {
        .name = "payStatus",
        .number = PBMChaseCenterInfo_FieldNumber_PayStatus,
        .hasIndex = 10,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterInfo_Storage, payStatus),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameType",
        .number = PBMChaseCenterInfo_FieldNumber_GameType,
        .hasIndex = 11,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMChaseCenterInfo_Storage, gameType),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "startGameName",
        .number = PBMChaseCenterInfo_FieldNumber_StartGameName,
        .hasIndex = 12,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_Storage, startGameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "startGameId",
        .number = PBMChaseCenterInfo_FieldNumber_StartGameId,
        .hasIndex = 13,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_Storage, startGameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMChaseCenterInfo class]
                                              rootClass:[PBMChaseCenterRoot class]
                                                   file:PBMChaseCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMChaseCenterInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMChaseCenterInfo_ChaseCenterItem

@implementation PBMChaseCenterInfo_ChaseCenterItem

@dynamic hasGameName, gameName;
@dynamic hasDrawNumbers, drawNumbers;
@dynamic hasChaseState, chaseState;
@dynamic hasWinInfo, winInfo;
@dynamic hasProjectId, projectId;

typedef struct PBMChaseCenterInfo_ChaseCenterItem_Storage {
  uint32_t _has_storage_[1];
  NSString *gameName;
  NSString *drawNumbers;
  NSString *chaseState;
  NSString *winInfo;
  int64_t projectId;
} PBMChaseCenterInfo_ChaseCenterItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameName",
        .number = PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_GameName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_ChaseCenterItem_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "drawNumbers",
        .number = PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_DrawNumbers,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_ChaseCenterItem_Storage, drawNumbers),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "chaseState",
        .number = PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_ChaseState,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_ChaseCenterItem_Storage, chaseState),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "winInfo",
        .number = PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_WinInfo,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChaseCenterInfo_ChaseCenterItem_Storage, winInfo),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "projectId",
        .number = PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_ProjectId,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMChaseCenterInfo_ChaseCenterItem_Storage, projectId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMChaseCenterInfo_ChaseCenterItem class]
                                              rootClass:[PBMChaseCenterRoot class]
                                                   file:PBMChaseCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMChaseCenterInfo_ChaseCenterItem_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMStopChaseParam

@implementation PBMStopChaseParam

@dynamic hasChaseId, chaseId;

typedef struct PBMStopChaseParam_Storage {
  uint32_t _has_storage_[1];
  int64_t chaseId;
} PBMStopChaseParam_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "chaseId",
        .number = PBMStopChaseParam_FieldNumber_ChaseId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMStopChaseParam_Storage, chaseId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMStopChaseParam class]
                                              rootClass:[PBMChaseCenterRoot class]
                                                   file:PBMChaseCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMStopChaseParam_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
