// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chase_center.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - PBMChaseCenterRoot

@interface PBMChaseCenterRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PBMChaseCenterItem

typedef GPB_ENUM(PBMChaseCenterItem_FieldNumber) {
  PBMChaseCenterItem_FieldNumber_ChaseId = 1,
  PBMChaseCenterItem_FieldNumber_GameType = 2,
  PBMChaseCenterItem_FieldNumber_StartTime = 3,
  PBMChaseCenterItem_FieldNumber_TotalIssueCount = 4,
  PBMChaseCenterItem_FieldNumber_ChasedIssueCount = 5,
};

//追号中心item
@interface PBMChaseCenterItem : GPBMessage

//追号id
@property(nonatomic, readwrite) BOOL hasChaseId;
@property(nonatomic, readwrite) int64_t chaseId;

//彩中id
@property(nonatomic, readwrite) BOOL hasGameType;
@property(nonatomic, readwrite) int32_t gameType;

//发起时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

//总期数
@property(nonatomic, readwrite) BOOL hasTotalIssueCount;
@property(nonatomic, readwrite) int32_t totalIssueCount;

//已追期数
@property(nonatomic, readwrite) BOOL hasChasedIssueCount;
@property(nonatomic, readwrite) int32_t chasedIssueCount;

@end

#pragma mark - PBMChaseCenterList

typedef GPB_ENUM(PBMChaseCenterList_FieldNumber) {
  PBMChaseCenterList_FieldNumber_ChaseCenterItemsArray = 1,
  PBMChaseCenterList_FieldNumber_TotalItemCount = 2,
};

@interface PBMChaseCenterList : GPBMessage

//追号中心item list
// |chaseCenterItemsArray| contains |PBMChaseCenterItem|
@property(nonatomic, readwrite, strong) NSMutableArray *chaseCenterItemsArray;

//列表总数；
@property(nonatomic, readwrite) BOOL hasTotalItemCount;
@property(nonatomic, readwrite) int32_t totalItemCount;

@end

#pragma mark - PBMChaseCenterInfo

typedef GPB_ENUM(PBMChaseCenterInfo_FieldNumber) {
  PBMChaseCenterInfo_FieldNumber_StartTime = 1,
  PBMChaseCenterInfo_FieldNumber_TotalIssueCount = 2,
  PBMChaseCenterInfo_FieldNumber_ChasedIssueCount = 3,
  PBMChaseCenterInfo_FieldNumber_ChaseTotalMoney = 4,
  PBMChaseCenterInfo_FieldNumber_ChasedMoney = 5,
  PBMChaseCenterInfo_FieldNumber_ChasedState = 6,
  PBMChaseCenterInfo_FieldNumber_Quantity = 7,
  PBMChaseCenterInfo_FieldNumber_Multiple = 8,
  PBMChaseCenterInfo_FieldNumber_BetContent = 9,
  PBMChaseCenterInfo_FieldNumber_ChaseInfoArray = 10,
  PBMChaseCenterInfo_FieldNumber_PayStatus = 11,
  PBMChaseCenterInfo_FieldNumber_GameType = 12,
  PBMChaseCenterInfo_FieldNumber_StartGameName = 13,
  PBMChaseCenterInfo_FieldNumber_StartGameId = 14,
};

@interface PBMChaseCenterInfo : GPBMessage

//发起时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

//总期数
@property(nonatomic, readwrite) BOOL hasTotalIssueCount;
@property(nonatomic, readwrite) int32_t totalIssueCount;

//已追期数
@property(nonatomic, readwrite) BOOL hasChasedIssueCount;
@property(nonatomic, readwrite) int32_t chasedIssueCount;

//总金额
@property(nonatomic, readwrite) BOOL hasChaseTotalMoney;
@property(nonatomic, readwrite) int64_t chaseTotalMoney;

//追号金额
@property(nonatomic, readwrite) BOOL hasChasedMoney;
@property(nonatomic, readwrite) int64_t chasedMoney;

//追号状态
@property(nonatomic, readwrite) BOOL hasChasedState;
@property(nonatomic, readwrite) int32_t chasedState;

//注数
@property(nonatomic, readwrite) BOOL hasQuantity;
@property(nonatomic, readwrite) int64_t quantity;

//倍数
@property(nonatomic, readwrite) BOOL hasMultiple;
@property(nonatomic, readwrite) int64_t multiple;

//投注内容 
@property(nonatomic, readwrite) BOOL hasBetContent;
@property(nonatomic, readwrite, copy) NSString *betContent;

//追号内容item list
// |chaseInfoArray| contains |PBMChaseCenterInfo_ChaseCenterItem|
@property(nonatomic, readwrite, strong) NSMutableArray *chaseInfoArray;

//支付状态  1:未付款 2:部分支付 3:支付完成  ？是否需要
@property(nonatomic, readwrite) BOOL hasPayStatus;
@property(nonatomic, readwrite) int32_t payStatus;

//彩中类型id
@property(nonatomic, readwrite) BOOL hasGameType;
@property(nonatomic, readwrite) int32_t gameType;

//追号第一期的期号
@property(nonatomic, readwrite) BOOL hasStartGameName;
@property(nonatomic, readwrite, copy) NSString *startGameName;

//追号第一期的期号主键id
@property(nonatomic, readwrite) BOOL hasStartGameId;
@property(nonatomic, readwrite) int64_t startGameId;

@end

#pragma mark - PBMChaseCenterInfo_ChaseCenterItem

typedef GPB_ENUM(PBMChaseCenterInfo_ChaseCenterItem_FieldNumber) {
  PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_GameName = 1,
  PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_DrawNumbers = 2,
  PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_ChaseState = 3,
  PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_WinInfo = 4,
  PBMChaseCenterInfo_ChaseCenterItem_FieldNumber_ProjectId = 5,
};

@interface PBMChaseCenterInfo_ChaseCenterItem : GPBMessage

//期号
@property(nonatomic, readwrite) BOOL hasGameName;
@property(nonatomic, readwrite, copy) NSString *gameName;

//开奖号码，根据彩中解析
@property(nonatomic, readwrite) BOOL hasDrawNumbers;
@property(nonatomic, readwrite, copy) NSString *drawNumbers;

//出票状态
@property(nonatomic, readwrite) BOOL hasChaseState;
@property(nonatomic, readwrite, copy) NSString *chaseState;

//中奖情况
@property(nonatomic, readwrite) BOOL hasWinInfo;
@property(nonatomic, readwrite, copy) NSString *winInfo;

//方案id
@property(nonatomic, readwrite) BOOL hasProjectId;
@property(nonatomic, readwrite) int64_t projectId;

@end

#pragma mark - PBMStopChaseParam

typedef GPB_ENUM(PBMStopChaseParam_FieldNumber) {
  PBMStopChaseParam_FieldNumber_ChaseId = 1,
};

@interface PBMStopChaseParam : GPBMessage

//追号id
@property(nonatomic, readwrite) BOOL hasChaseId;
@property(nonatomic, readwrite) int64_t chaseId;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
