// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class PBMUpdateVersion;

#pragma mark - Enum PBMDeviceRegisterType

typedef GPB_ENUM(PBMDeviceRegisterType) {
  //    DeviceRegisterStartup   = 0;    // 启动, 客户端不用传启动统计
  PBMDeviceRegisterType_DeviceRegisterActivate = 1,

  // 升级
  PBMDeviceRegisterType_DeviceRegisterUpdate = 2,

  // 推送设备号更新
  PBMDeviceRegisterType_DevicePushTokenUpdate = 3,
};

GPBEnumDescriptor *PBMDeviceRegisterType_EnumDescriptor(void);

BOOL PBMDeviceRegisterType_IsValidValue(int32_t value);


#pragma mark - PBMCommonRoot

@interface PBMCommonRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PBMDeviceRegister

typedef GPB_ENUM(PBMDeviceRegister_FieldNumber) {
  PBMDeviceRegister_FieldNumber_ActiveType = 1,
  PBMDeviceRegister_FieldNumber_DeviceId = 2,
  PBMDeviceRegister_FieldNumber_PushToken = 3,
};

// 注册设备, post参数
@interface PBMDeviceRegister : GPBMessage

// 类型
@property(nonatomic, readwrite) BOOL hasActiveType;
@property(nonatomic, readwrite) int32_t activeType;

// 设备号
@property(nonatomic, readwrite) BOOL hasDeviceId;
@property(nonatomic, readwrite, copy) NSString *deviceId;

// 推送设备号
@property(nonatomic, readwrite) BOOL hasPushToken;
@property(nonatomic, readwrite, copy) NSString *pushToken;

@end

#pragma mark - PBMDeviceGuid

typedef GPB_ENUM(PBMDeviceGuid_FieldNumber) {
  PBMDeviceGuid_FieldNumber_Guid = 1,
};

// 注册设备, 返回结果
@interface PBMDeviceGuid : GPBMessage

// GUID
@property(nonatomic, readwrite) BOOL hasGuid;
@property(nonatomic, readwrite, copy) NSString *guid;

@end

#pragma mark - PBMSyncDate

typedef GPB_ENUM(PBMSyncDate_FieldNumber) {
  PBMSyncDate_FieldNumber_Date = 1,
};

// 获取服务器时间
@interface PBMSyncDate : GPBMessage

// 服务器时间
@property(nonatomic, readwrite) BOOL hasDate;
@property(nonatomic, readwrite, copy) NSString *date;

@end

#pragma mark - PBMLoadingPage

typedef GPB_ENUM(PBMLoadingPage_FieldNumber) {
  PBMLoadingPage_FieldNumber_ImageURL = 1,
  PBMLoadingPage_FieldNumber_EventURL = 2,
  PBMLoadingPage_FieldNumber_UpdateInfo = 3,
};

// 启动页
@interface PBMLoadingPage : GPBMessage

// 图片地址
@property(nonatomic, readwrite) BOOL hasImageURL;
@property(nonatomic, readwrite, copy) NSString *imageURL;

// 点击事件
@property(nonatomic, readwrite) BOOL hasEventURL;
@property(nonatomic, readwrite, copy) NSString *eventURL;

// 升级信息
@property(nonatomic, readwrite) BOOL hasUpdateInfo;
@property(nonatomic, readwrite, strong) PBMUpdateVersion *updateInfo;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
