// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: draw_trend.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - PBMDrawTrendRoot

@interface PBMDrawTrendRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PBMDrawTrend

typedef GPB_ENUM(PBMDrawTrend_FieldNumber) {
  PBMDrawTrend_FieldNumber_DrawResultArray = 1,
  PBMDrawTrend_FieldNumber_AllCountArray = 2,
  PBMDrawTrend_FieldNumber_InitMissArray = 3,
  PBMDrawTrend_FieldNumber_AvgMissArray = 4,
  PBMDrawTrend_FieldNumber_MaxMissArray = 5,
  PBMDrawTrend_FieldNumber_MaxComboArray = 6,
};

// 走势图
@interface PBMDrawTrend : GPBMessage

// 近200期开奖号码
// |drawResultArray| contains |PBMDrawTrend_Result|
@property(nonatomic, readwrite, strong) NSMutableArray *drawResultArray;

// 出现次数
@property(nonatomic, readwrite, strong) GPBInt32Array *allCountArray;

// 初始遗漏值
@property(nonatomic, readwrite, strong) GPBInt32Array *initMissArray;
- (GPBInt32Array *)initMissArray GPB_METHOD_FAMILY_NONE;

// 平均遗漏值
@property(nonatomic, readwrite, strong) GPBInt32Array *avgMissArray;

// 最大遗漏值
@property(nonatomic, readwrite, strong) GPBInt32Array *maxMissArray;

// 最大连出值
@property(nonatomic, readwrite, strong) GPBInt32Array *maxComboArray;

@end

#pragma mark - PBMDrawTrend_Result

typedef GPB_ENUM(PBMDrawTrend_Result_FieldNumber) {
  PBMDrawTrend_Result_FieldNumber_NumbersArray = 1,
  PBMDrawTrend_Result_FieldNumber_GameName = 2,
};

// 开奖结果
@interface PBMDrawTrend_Result : GPBMessage

// 开奖号码
@property(nonatomic, readwrite, strong) GPBInt32Array *numbersArray;

// 期号
@property(nonatomic, readwrite) BOOL hasGameName;
@property(nonatomic, readwrite, copy) NSString *gameName;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
