// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: draw_notice.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "DrawNotice.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PBMDrawNoticeRoot

@implementation PBMDrawNoticeRoot

@end

static GPBFileDescriptor *PBMDrawNoticeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"Dacai.Protobuf"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBMDrawHomeList

@implementation PBMDrawHomeList

@dynamic itemsArray;
@dynamic hasShareParam, shareParam;

typedef struct PBMDrawHomeList_Storage {
  uint32_t _has_storage_[1];
  NSMutableArray *itemsArray;
  PBMDrawHomeList_ShareItem *shareParam;
} PBMDrawHomeList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemsArray",
        .number = PBMDrawHomeList_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawHomeList_Storage, itemsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawHomeList_Item),
        .fieldOptions = NULL,
      },
      {
        .name = "shareParam",
        .number = PBMDrawHomeList_FieldNumber_ShareParam,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawHomeList_Storage, shareParam),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawHomeList_ShareItem),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawHomeList class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawHomeList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawHomeList_ShareItem

@implementation PBMDrawHomeList_ShareItem

@dynamic hasShareTitle, shareTitle;
@dynamic hasShareContent, shareContent;
@dynamic hasShareURL, shareURL;

typedef struct PBMDrawHomeList_ShareItem_Storage {
  uint32_t _has_storage_[1];
  NSString *shareTitle;
  NSString *shareContent;
  NSString *shareURL;
} PBMDrawHomeList_ShareItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "shareTitle",
        .number = PBMDrawHomeList_ShareItem_FieldNumber_ShareTitle,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_ShareItem_Storage, shareTitle),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "shareContent",
        .number = PBMDrawHomeList_ShareItem_FieldNumber_ShareContent,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_ShareItem_Storage, shareContent),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "shareURL",
        .number = PBMDrawHomeList_ShareItem_FieldNumber_ShareURL,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_ShareItem_Storage, shareURL),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\001\003\005\241!!\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawHomeList_ShareItem class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawHomeList_ShareItem_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawHomeList_Item

@implementation PBMDrawHomeList_Item

@dynamic hasGameType, gameType;
@dynamic hasGameId, gameId;
@dynamic hasGameName, gameName;
@dynamic hasDrawTime, drawTime;
@dynamic hasResluts, resluts;
@dynamic hasTotalGames, totalGames;
@dynamic hasEndedGames, endedGames;

typedef struct PBMDrawHomeList_Item_Storage {
  uint32_t _has_storage_[1];
  int32_t gameType;
  int32_t totalGames;
  int32_t endedGames;
  NSString *gameName;
  NSString *drawTime;
  NSString *resluts;
  int64_t gameId;
} PBMDrawHomeList_Item_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameType",
        .number = PBMDrawHomeList_Item_FieldNumber_GameType,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, gameType),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameId",
        .number = PBMDrawHomeList_Item_FieldNumber_GameId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, gameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameName",
        .number = PBMDrawHomeList_Item_FieldNumber_GameName,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "drawTime",
        .number = PBMDrawHomeList_Item_FieldNumber_DrawTime,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, drawTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "resluts",
        .number = PBMDrawHomeList_Item_FieldNumber_Resluts,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, resluts),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "totalGames",
        .number = PBMDrawHomeList_Item_FieldNumber_TotalGames,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, totalGames),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "endedGames",
        .number = PBMDrawHomeList_Item_FieldNumber_EndedGames,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawHomeList_Item_Storage, endedGames),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawHomeList_Item class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawHomeList_Item_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawNumDetailList

@implementation PBMDrawNumDetailList

@dynamic itemsArray;
@dynamic hasTotal, total;

typedef struct PBMDrawNumDetailList_Storage {
  uint32_t _has_storage_[1];
  int32_t total;
  NSMutableArray *itemsArray;
} PBMDrawNumDetailList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemsArray",
        .number = PBMDrawNumDetailList_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawNumDetailList_Storage, itemsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawNumDetailList_Item),
        .fieldOptions = NULL,
      },
      {
        .name = "total",
        .number = PBMDrawNumDetailList_FieldNumber_Total,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawNumDetailList_Storage, total),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawNumDetailList class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawNumDetailList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawNumDetailList_Item

@implementation PBMDrawNumDetailList_Item

@dynamic hasGameId, gameId;
@dynamic hasGameName, gameName;
@dynamic hasDrawTime, drawTime;
@dynamic hasResluts, resluts;
@dynamic hasGlobalSurplus, globalSurplus;
@dynamic hasGlobalAmount, globalAmount;
@dynamic winCountArray;
@dynamic winAmountArray;

typedef struct PBMDrawNumDetailList_Item_Storage {
  uint32_t _has_storage_[1];
  NSString *gameName;
  NSString *drawTime;
  NSString *resluts;
  GPBInt64Array *winCountArray;
  GPBInt64Array *winAmountArray;
  int64_t gameId;
  int64_t globalSurplus;
  int64_t globalAmount;
} PBMDrawNumDetailList_Item_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameId",
        .number = PBMDrawNumDetailList_Item_FieldNumber_GameId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, gameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameName",
        .number = PBMDrawNumDetailList_Item_FieldNumber_GameName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "drawTime",
        .number = PBMDrawNumDetailList_Item_FieldNumber_DrawTime,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, drawTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "resluts",
        .number = PBMDrawNumDetailList_Item_FieldNumber_Resluts,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, resluts),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "globalSurplus",
        .number = PBMDrawNumDetailList_Item_FieldNumber_GlobalSurplus,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, globalSurplus),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "globalAmount",
        .number = PBMDrawNumDetailList_Item_FieldNumber_GlobalAmount,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, globalAmount),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "winCountArray",
        .number = PBMDrawNumDetailList_Item_FieldNumber_WinCountArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, winCountArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "winAmountArray",
        .number = PBMDrawNumDetailList_Item_FieldNumber_WinAmountArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawNumDetailList_Item_Storage, winAmountArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawNumDetailList_Item class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawNumDetailList_Item_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawZcDetailList

@implementation PBMDrawZcDetailList

@dynamic itemsArray;
@dynamic hasTotal, total;

typedef struct PBMDrawZcDetailList_Storage {
  uint32_t _has_storage_[1];
  int32_t total;
  NSMutableArray *itemsArray;
} PBMDrawZcDetailList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemsArray",
        .number = PBMDrawZcDetailList_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawZcDetailList_Storage, itemsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawZcDetailList_Item),
        .fieldOptions = NULL,
      },
      {
        .name = "total",
        .number = PBMDrawZcDetailList_FieldNumber_Total,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawZcDetailList_Storage, total),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawZcDetailList class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawZcDetailList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawZcDetailList_Item

@implementation PBMDrawZcDetailList_Item

@dynamic hasGameId, gameId;
@dynamic hasGameName, gameName;
@dynamic hasDrawTime, drawTime;
@dynamic hasResluts, resluts;
@dynamic hasZc14GlobalSurplus, zc14GlobalSurplus;
@dynamic hasZc14GlobalAmount, zc14GlobalAmount;
@dynamic zc14WinCountArray;
@dynamic zc14WinAmountArray;
@dynamic hasZc9GlobalSurplus, zc9GlobalSurplus;
@dynamic hasZc9GlobalAmount, zc9GlobalAmount;
@dynamic hasZc9WinCount, zc9WinCount;
@dynamic hasZc9WinAmount, zc9WinAmount;

typedef struct PBMDrawZcDetailList_Item_Storage {
  uint32_t _has_storage_[1];
  NSString *gameName;
  NSString *drawTime;
  NSString *resluts;
  GPBInt64Array *zc14WinCountArray;
  GPBInt64Array *zc14WinAmountArray;
  int64_t gameId;
  int64_t zc14GlobalSurplus;
  int64_t zc14GlobalAmount;
  int64_t zc9GlobalSurplus;
  int64_t zc9GlobalAmount;
  int64_t zc9WinCount;
  int64_t zc9WinAmount;
} PBMDrawZcDetailList_Item_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameId",
        .number = PBMDrawZcDetailList_Item_FieldNumber_GameId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, gameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameName",
        .number = PBMDrawZcDetailList_Item_FieldNumber_GameName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "drawTime",
        .number = PBMDrawZcDetailList_Item_FieldNumber_DrawTime,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, drawTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "resluts",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Resluts,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, resluts),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc14GlobalSurplus",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc14GlobalSurplus,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc14GlobalSurplus),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc14GlobalAmount",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc14GlobalAmount,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc14GlobalAmount),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc14WinCountArray",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc14WinCountArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc14WinCountArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc14WinAmountArray",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc14WinAmountArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc14WinAmountArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc9GlobalSurplus",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc9GlobalSurplus,
        .hasIndex = 8,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc9GlobalSurplus),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc9GlobalAmount",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc9GlobalAmount,
        .hasIndex = 9,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc9GlobalAmount),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc9WinCount",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc9WinCount,
        .hasIndex = 10,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc9WinCount),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "zc9WinAmount",
        .number = PBMDrawZcDetailList_Item_FieldNumber_Zc9WinAmount,
        .hasIndex = 11,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawZcDetailList_Item_Storage, zc9WinAmount),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawZcDetailList_Item class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawZcDetailList_Item_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawZcMatchList

@implementation PBMDrawZcMatchList

@dynamic matchesArray;

typedef struct PBMDrawZcMatchList_Storage {
  uint32_t _has_storage_[1];
  NSMutableArray *matchesArray;
} PBMDrawZcMatchList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "matchesArray",
        .number = PBMDrawZcMatchList_FieldNumber_MatchesArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawZcMatchList_Storage, matchesArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawZcMatchList_Match),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawZcMatchList class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawZcMatchList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawZcMatchList_Match

@implementation PBMDrawZcMatchList_Match

@dynamic hasOrder, order;
@dynamic hasResluts, resluts;
@dynamic hasHomeName, homeName;
@dynamic hasAwayName, awayName;

typedef struct PBMDrawZcMatchList_Match_Storage {
  uint32_t _has_storage_[1];
  int32_t order;
  NSString *resluts;
  NSString *homeName;
  NSString *awayName;
} PBMDrawZcMatchList_Match_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "order",
        .number = PBMDrawZcMatchList_Match_FieldNumber_Order,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawZcMatchList_Match_Storage, order),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "resluts",
        .number = PBMDrawZcMatchList_Match_FieldNumber_Resluts,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcMatchList_Match_Storage, resluts),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeName",
        .number = PBMDrawZcMatchList_Match_FieldNumber_HomeName,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcMatchList_Match_Storage, homeName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayName",
        .number = PBMDrawZcMatchList_Match_FieldNumber_AwayName,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawZcMatchList_Match_Storage, awayName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawZcMatchList_Match class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawZcMatchList_Match_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawSportDetailList

@implementation PBMDrawSportDetailList

@dynamic hasGameId, gameId;
@dynamic hasGameName, gameName;
@dynamic itemsArray;
@dynamic gamesArray;

typedef struct PBMDrawSportDetailList_Storage {
  uint32_t _has_storage_[1];
  NSString *gameName;
  NSMutableArray *itemsArray;
  NSMutableArray *gamesArray;
  int64_t gameId;
} PBMDrawSportDetailList_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameId",
        .number = PBMDrawSportDetailList_FieldNumber_GameId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawSportDetailList_Storage, gameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameName",
        .number = PBMDrawSportDetailList_FieldNumber_GameName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "itemsArray",
        .number = PBMDrawSportDetailList_FieldNumber_ItemsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawSportDetailList_Storage, itemsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawSportDetailList_Item),
        .fieldOptions = NULL,
      },
      {
        .name = "gamesArray",
        .number = PBMDrawSportDetailList_FieldNumber_GamesArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMDrawSportDetailList_Storage, gamesArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMDrawSportDetailList_Game),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawSportDetailList class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawSportDetailList_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawSportDetailList_Item

@implementation PBMDrawSportDetailList_Item

@dynamic hasCompetition, competition;
@dynamic hasOrderNumber, orderNumber;
@dynamic hasStratTime, stratTime;
@dynamic hasHomeName, homeName;
@dynamic hasAwayName, awayName;
@dynamic hasHomeScore, homeScore;
@dynamic hasAwayScore, awayScore;
@dynamic hasResluts, resluts;
@dynamic hasBalance, balance;
@dynamic hasHomeURL, homeURL;
@dynamic hasAwayURL, awayURL;

typedef struct PBMDrawSportDetailList_Item_Storage {
  uint32_t _has_storage_[1];
  int32_t homeScore;
  int32_t awayScore;
  NSString *competition;
  NSString *orderNumber;
  NSString *stratTime;
  NSString *homeName;
  NSString *awayName;
  NSString *resluts;
  NSString *balance;
  NSString *homeURL;
  NSString *awayURL;
} PBMDrawSportDetailList_Item_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "competition",
        .number = PBMDrawSportDetailList_Item_FieldNumber_Competition,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, competition),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "orderNumber",
        .number = PBMDrawSportDetailList_Item_FieldNumber_OrderNumber,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, orderNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "stratTime",
        .number = PBMDrawSportDetailList_Item_FieldNumber_StratTime,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, stratTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeName",
        .number = PBMDrawSportDetailList_Item_FieldNumber_HomeName,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, homeName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayName",
        .number = PBMDrawSportDetailList_Item_FieldNumber_AwayName,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, awayName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeScore",
        .number = PBMDrawSportDetailList_Item_FieldNumber_HomeScore,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, homeScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayScore",
        .number = PBMDrawSportDetailList_Item_FieldNumber_AwayScore,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, awayScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "resluts",
        .number = PBMDrawSportDetailList_Item_FieldNumber_Resluts,
        .hasIndex = 7,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, resluts),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "balance",
        .number = PBMDrawSportDetailList_Item_FieldNumber_Balance,
        .hasIndex = 8,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, balance),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeURL",
        .number = PBMDrawSportDetailList_Item_FieldNumber_HomeURL,
        .hasIndex = 9,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, homeURL),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayURL",
        .number = PBMDrawSportDetailList_Item_FieldNumber_AwayURL,
        .hasIndex = 10,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Item_Storage, awayURL),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\002\n\004\241!!\000\013\004\241!!\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawSportDetailList_Item class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawSportDetailList_Item_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end

#pragma mark - PBMDrawSportDetailList_Game

@implementation PBMDrawSportDetailList_Game

@dynamic hasGameId, gameId;
@dynamic hasGameName, gameName;
@dynamic hasGameStatus, gameStatus;

typedef struct PBMDrawSportDetailList_Game_Storage {
  uint32_t _has_storage_[1];
  int32_t gameStatus;
  NSString *gameName;
  int64_t gameId;
} PBMDrawSportDetailList_Game_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gameId",
        .number = PBMDrawSportDetailList_Game_FieldNumber_GameId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMDrawSportDetailList_Game_Storage, gameId),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameName",
        .number = PBMDrawSportDetailList_Game_FieldNumber_GameName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMDrawSportDetailList_Game_Storage, gameName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "gameStatus",
        .number = PBMDrawSportDetailList_Game_FieldNumber_GameStatus,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMDrawSportDetailList_Game_Storage, gameStatus),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMDrawSportDetailList_Game class]
                                              rootClass:[PBMDrawNoticeRoot class]
                                                   file:PBMDrawNoticeRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMDrawSportDetailList_Game_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
