// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: football_data_center.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class PBMFootAnalysisDetail_MatchInfoTitle;
@class PBMFootAnalysis_MatchFutureItem;
@class PBMFootOddsHandicap_OddsHandItem;
@class PBMFootballHeader;
GPB_ENUM_FWD_DECLARE(PBMFootballEvent);
GPB_ENUM_FWD_DECLARE(PBMFootballMatchStatus);


#pragma mark - PBMFootballDataCenterRoot

@interface PBMFootballDataCenterRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PBMFootballHeader

typedef GPB_ENUM(PBMFootballHeader_FieldNumber) {
  PBMFootballHeader_FieldNumber_HomeTeamIcon = 1,
  PBMFootballHeader_FieldNumber_AwayTeamIcon = 2,
  PBMFootballHeader_FieldNumber_HomeTeamName = 3,
  PBMFootballHeader_FieldNumber_AwayTeamName = 4,
  PBMFootballHeader_FieldNumber_HomeTeamRank = 5,
  PBMFootballHeader_FieldNumber_AwayTeamRank = 6,
  PBMFootballHeader_FieldNumber_StartTime = 7,
  PBMFootballHeader_FieldNumber_Status = 8,
  PBMFootballHeader_FieldNumber_HomeScore = 9,
  PBMFootballHeader_FieldNumber_AwayScore = 10,
  PBMFootballHeader_FieldNumber_HomeHalfScore = 11,
  PBMFootballHeader_FieldNumber_AwayHalfScore = 12,
  PBMFootballHeader_FieldNumber_HalfStartTime = 13,
  PBMFootballHeader_FieldNumber_Focus = 14,
};

// 头部信息
@interface PBMFootballHeader : GPBMessage

// 主队图标
@property(nonatomic, readwrite) BOOL hasHomeTeamIcon;
@property(nonatomic, readwrite, copy) NSString *homeTeamIcon;

// 客队图标
@property(nonatomic, readwrite) BOOL hasAwayTeamIcon;
@property(nonatomic, readwrite, copy) NSString *awayTeamIcon;

// 主队名称
@property(nonatomic, readwrite) BOOL hasHomeTeamName;
@property(nonatomic, readwrite, copy) NSString *homeTeamName;

// 客队名称
@property(nonatomic, readwrite) BOOL hasAwayTeamName;
@property(nonatomic, readwrite, copy) NSString *awayTeamName;

// 主队排名
@property(nonatomic, readwrite) BOOL hasHomeTeamRank;
@property(nonatomic, readwrite, copy) NSString *homeTeamRank;

// 客队排名
@property(nonatomic, readwrite) BOOL hasAwayTeamRank;
@property(nonatomic, readwrite, copy) NSString *awayTeamRank;

// 开赛时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

// 比赛状态
@property(nonatomic, readwrite) BOOL hasStatus;
@property(nonatomic, readwrite) enum PBMFootballMatchStatus status;

// 主队全场得分
@property(nonatomic, readwrite) BOOL hasHomeScore;
@property(nonatomic, readwrite) int32_t homeScore;

// 客队全场得分
@property(nonatomic, readwrite) BOOL hasAwayScore;
@property(nonatomic, readwrite) int32_t awayScore;

// 主队半场得分
@property(nonatomic, readwrite) BOOL hasHomeHalfScore;
@property(nonatomic, readwrite) int32_t homeHalfScore;

// 客队半场得分
@property(nonatomic, readwrite) BOOL hasAwayHalfScore;
@property(nonatomic, readwrite) int32_t awayHalfScore;

// 半场开始时间
@property(nonatomic, readwrite) BOOL hasHalfStartTime;
@property(nonatomic, readwrite, copy) NSString *halfStartTime;

//是否关注
@property(nonatomic, readwrite) BOOL hasFocus;
@property(nonatomic, readwrite) BOOL focus;

@end

#pragma mark - PBMFootEventData

typedef GPB_ENUM(PBMFootEventData_FieldNumber) {
  PBMFootEventData_FieldNumber_MatchInfo = 1,
  PBMFootEventData_FieldNumber_EventListArray = 2,
  PBMFootEventData_FieldNumber_SkillListArray = 3,
  PBMFootEventData_FieldNumber_HomeListArray = 4,
  PBMFootEventData_FieldNumber_AwayListArray = 5,
};

// 赛事
@interface PBMFootEventData : GPBMessage

// 头部信息
@property(nonatomic, readwrite) BOOL hasMatchInfo;
@property(nonatomic, readwrite, strong) PBMFootballHeader *matchInfo;

// 赛事实况
// |eventListArray| contains |PBMFootEventData_MatchEventInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *eventListArray;

// 技术统计
// |skillListArray| contains |PBMFootEventData_SkillDetailInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *skillListArray;

// 主队球员列表
// |homeListArray| contains |PBMFootEventData_FormationDetailInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *homeListArray;

// 客队球员列表
// |awayListArray| contains |PBMFootEventData_FormationDetailInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *awayListArray;

@end

#pragma mark - PBMFootEventData_MatchEventInfo

typedef GPB_ENUM(PBMFootEventData_MatchEventInfo_FieldNumber) {
  PBMFootEventData_MatchEventInfo_FieldNumber_HomeOrAway = 1,
  PBMFootEventData_MatchEventInfo_FieldNumber_Player = 2,
  PBMFootEventData_MatchEventInfo_FieldNumber_Time = 3,
  PBMFootEventData_MatchEventInfo_FieldNumber_Event = 4,
};

// 赛事实况
@interface PBMFootEventData_MatchEventInfo : GPBMessage

// 主队事件 true, 客队事
@property(nonatomic, readwrite) BOOL hasHomeOrAway;
@property(nonatomic, readwrite) BOOL homeOrAway;

// 球员名件 false
@property(nonatomic, readwrite) BOOL hasPlayer;
@property(nonatomic, readwrite, copy) NSString *player;

// 发生时间
@property(nonatomic, readwrite) BOOL hasTime;
@property(nonatomic, readwrite) int32_t time;

// 事件类型
@property(nonatomic, readwrite) BOOL hasEvent;
@property(nonatomic, readwrite) enum PBMFootballEvent event;

@end

#pragma mark - PBMFootEventData_SkillDetailInfo

typedef GPB_ENUM(PBMFootEventData_SkillDetailInfo_FieldNumber) {
  PBMFootEventData_SkillDetailInfo_FieldNumber_Name = 1,
  PBMFootEventData_SkillDetailInfo_FieldNumber_HomeCount = 2,
  PBMFootEventData_SkillDetailInfo_FieldNumber_AwayCount = 3,
  PBMFootEventData_SkillDetailInfo_FieldNumber_HomeText = 4,
  PBMFootEventData_SkillDetailInfo_FieldNumber_AwayText = 5,
};

// 技术详情
@interface PBMFootEventData_SkillDetailInfo : GPBMessage

// 统计类型名称 eg.射门次数
@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

// 主队所占比例eg.40
@property(nonatomic, readwrite) BOOL hasHomeCount;
@property(nonatomic, readwrite) int32_t homeCount;

// 客队所占比例 eg.60
@property(nonatomic, readwrite) BOOL hasAwayCount;
@property(nonatomic, readwrite) int32_t awayCount;

// 主队显示文字e.g.”2”
@property(nonatomic, readwrite) BOOL hasHomeText;
@property(nonatomic, readwrite, copy) NSString *homeText;

// 客队显示文字 e.g.”3”
@property(nonatomic, readwrite) BOOL hasAwayText;
@property(nonatomic, readwrite, copy) NSString *awayText;

@end

#pragma mark - PBMFootEventData_FormationDetailInfo

typedef GPB_ENUM(PBMFootEventData_FormationDetailInfo_FieldNumber) {
  PBMFootEventData_FormationDetailInfo_FieldNumber_Number = 1,
  PBMFootEventData_FormationDetailInfo_FieldNumber_Player = 2,
  PBMFootEventData_FormationDetailInfo_FieldNumber_FirstPlayer = 3,
};

// 对阵信息
@interface PBMFootEventData_FormationDetailInfo : GPBMessage

// 球员号码
@property(nonatomic, readwrite) BOOL hasNumber;
@property(nonatomic, readwrite) int32_t number;

// 球员名称
@property(nonatomic, readwrite) BOOL hasPlayer;
@property(nonatomic, readwrite, copy) NSString *player;

// 是否是首发球员
@property(nonatomic, readwrite) BOOL hasFirstPlayer;
@property(nonatomic, readwrite) BOOL firstPlayer;

@end

#pragma mark - PBMFootAnalysis

typedef GPB_ENUM(PBMFootAnalysis_FieldNumber) {
  PBMFootAnalysis_FieldNumber_HomeWinTimes = 1,
  PBMFootAnalysis_FieldNumber_HistoryTieTimes = 2,
  PBMFootAnalysis_FieldNumber_AwayWinTimes = 3,
  PBMFootAnalysis_FieldNumber_HomeRecentStatusArray = 4,
  PBMFootAnalysis_FieldNumber_AwayRecentStatusArray = 5,
  PBMFootAnalysis_FieldNumber_HomeItem = 6,
  PBMFootAnalysis_FieldNumber_AwayItem = 7,
  PBMFootAnalysis_FieldNumber_MatchInfo = 8,
};

// 分析
@interface PBMFootAnalysis : GPBMessage

// 主队胜的次数
@property(nonatomic, readwrite) BOOL hasHomeWinTimes;
@property(nonatomic, readwrite) int32_t homeWinTimes;

// 平次数
@property(nonatomic, readwrite) BOOL hasHistoryTieTimes;
@property(nonatomic, readwrite) int32_t historyTieTimes;

// 客队胜的次数
@property(nonatomic, readwrite) BOOL hasAwayWinTimes;
@property(nonatomic, readwrite) int32_t awayWinTimes;

// 主队近期战绩 负-1 平0 ,胜1
@property(nonatomic, readwrite, strong) GPBInt32Array *homeRecentStatusArray;

// 客队近期胜战绩
@property(nonatomic, readwrite, strong) GPBInt32Array *awayRecentStatusArray;

// 主队未来对阵
@property(nonatomic, readwrite) BOOL hasHomeItem;
@property(nonatomic, readwrite, strong) PBMFootAnalysis_MatchFutureItem *homeItem;

// 客队未来对阵
@property(nonatomic, readwrite) BOOL hasAwayItem;
@property(nonatomic, readwrite, strong) PBMFootAnalysis_MatchFutureItem *awayItem;

// 头部信息
@property(nonatomic, readwrite) BOOL hasMatchInfo;
@property(nonatomic, readwrite, strong) PBMFootballHeader *matchInfo;

@end

#pragma mark - PBMFootAnalysis_MatchFutureItem

typedef GPB_ENUM(PBMFootAnalysis_MatchFutureItem_FieldNumber) {
  PBMFootAnalysis_MatchFutureItem_FieldNumber_StartTime = 1,
  PBMFootAnalysis_MatchFutureItem_FieldNumber_HomeTeamName = 2,
  PBMFootAnalysis_MatchFutureItem_FieldNumber_AwayTeamName = 3,
  PBMFootAnalysis_MatchFutureItem_FieldNumber_HomeIcon = 4,
  PBMFootAnalysis_MatchFutureItem_FieldNumber_AwayIcon = 5,
};

// 未来对阵
@interface PBMFootAnalysis_MatchFutureItem : GPBMessage

// 开始时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

// 主队名称
@property(nonatomic, readwrite) BOOL hasHomeTeamName;
@property(nonatomic, readwrite, copy) NSString *homeTeamName;

// 客队名称
@property(nonatomic, readwrite) BOOL hasAwayTeamName;
@property(nonatomic, readwrite, copy) NSString *awayTeamName;

// 主队图标
@property(nonatomic, readwrite) BOOL hasHomeIcon;
@property(nonatomic, readwrite, copy) NSString *homeIcon;

// 客队图标
@property(nonatomic, readwrite) BOOL hasAwayIcon;
@property(nonatomic, readwrite, copy) NSString *awayIcon;

@end

#pragma mark - PBMFootAnalysisDetail

typedef GPB_ENUM(PBMFootAnalysisDetail_FieldNumber) {
  PBMFootAnalysisDetail_FieldNumber_HomeHistory = 1,
  PBMFootAnalysisDetail_FieldNumber_HomeRecent = 2,
  PBMFootAnalysisDetail_FieldNumber_AwayRecent = 3,
  PBMFootAnalysisDetail_FieldNumber_HomeFuture = 4,
  PBMFootAnalysisDetail_FieldNumber_AwayFuture = 5,
};

// 分析详情
@interface PBMFootAnalysisDetail : GPBMessage

// 历史交锋
@property(nonatomic, readwrite) BOOL hasHomeHistory;
@property(nonatomic, readwrite, strong) PBMFootAnalysisDetail_MatchInfoTitle *homeHistory;

// 主队近期战绩
@property(nonatomic, readwrite) BOOL hasHomeRecent;
@property(nonatomic, readwrite, strong) PBMFootAnalysisDetail_MatchInfoTitle *homeRecent;

// 客队近期战绩
@property(nonatomic, readwrite) BOOL hasAwayRecent;
@property(nonatomic, readwrite, strong) PBMFootAnalysisDetail_MatchInfoTitle *awayRecent;

// 主队未来对阵
@property(nonatomic, readwrite) BOOL hasHomeFuture;
@property(nonatomic, readwrite, strong) PBMFootAnalysisDetail_MatchInfoTitle *homeFuture;

// 客队未来对阵
@property(nonatomic, readwrite) BOOL hasAwayFuture;
@property(nonatomic, readwrite, strong) PBMFootAnalysisDetail_MatchInfoTitle *awayFuture;

@end

#pragma mark - PBMFootAnalysisDetail_MatchInfoTitle

typedef GPB_ENUM(PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber) {
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalWin = 1,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalTie = 2,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalLose = 3,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeWinTimes = 4,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeTieTimes = 5,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeLoseTimes = 6,
  PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_MatchInfoListArray = 7,
};

@interface PBMFootAnalysisDetail_MatchInfoTitle : GPBMessage

// 总的胜的次数
@property(nonatomic, readwrite) BOOL hasTotalWin;
@property(nonatomic, readwrite) int32_t totalWin;

// 总的平次数
@property(nonatomic, readwrite) BOOL hasTotalTie;
@property(nonatomic, readwrite) int32_t totalTie;

// 总的负的次数
@property(nonatomic, readwrite) BOOL hasTotalLose;
@property(nonatomic, readwrite) int32_t totalLose;

// 主场胜的次数
@property(nonatomic, readwrite) BOOL hasHomeWinTimes;
@property(nonatomic, readwrite) int32_t homeWinTimes;

// 主场平次数
@property(nonatomic, readwrite) BOOL hasHomeTieTimes;
@property(nonatomic, readwrite) int32_t homeTieTimes;

// 主场负的次数
@property(nonatomic, readwrite) BOOL hasHomeLoseTimes;
@property(nonatomic, readwrite) int32_t homeLoseTimes;

// 赛事数组
// |matchInfoListArray| contains |PBMFootAnalysisDetail_MatchInfoDetailInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *matchInfoListArray;

@end

#pragma mark - PBMFootAnalysisDetail_MatchInfoDetailInfo

typedef GPB_ENUM(PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber) {
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_Completion = 1,
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_StartTime = 2,
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_HomeTeamName = 3,
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_AwayTeamName = 4,
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_HomeScore = 5,
  PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_AwayScore = 6,
};

@interface PBMFootAnalysisDetail_MatchInfoDetailInfo : GPBMessage

// 赛事名称
@property(nonatomic, readwrite) BOOL hasCompletion;
@property(nonatomic, readwrite, copy) NSString *completion;

// 开始时间
@property(nonatomic, readwrite) BOOL hasStartTime;
@property(nonatomic, readwrite, copy) NSString *startTime;

// 主队名称
@property(nonatomic, readwrite) BOOL hasHomeTeamName;
@property(nonatomic, readwrite, copy) NSString *homeTeamName;

// 客队名称
@property(nonatomic, readwrite) BOOL hasAwayTeamName;
@property(nonatomic, readwrite, copy) NSString *awayTeamName;

// 主队得分
@property(nonatomic, readwrite) BOOL hasHomeScore;
@property(nonatomic, readwrite) int32_t homeScore;

// 客队得分
@property(nonatomic, readwrite) BOOL hasAwayScore;
@property(nonatomic, readwrite) int32_t awayScore;

@end

#pragma mark - PBMFootIntegral

typedef GPB_ENUM(PBMFootIntegral_FieldNumber) {
  PBMFootIntegral_FieldNumber_IntegralListArray = 1,
  PBMFootIntegral_FieldNumber_AreaNameArray = 2,
  PBMFootIntegral_FieldNumber_AreaColorArray = 3,
  PBMFootIntegral_FieldNumber_MatchInfo = 4,
  PBMFootIntegral_FieldNumber_Title = 5,
};

// 积分
@interface PBMFootIntegral : GPBMessage

// 积分榜列表
// |integralListArray| contains |PBMFootIntegral_IntegralDetailInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *integralListArray;

// 区域名称数组
// |areaNameArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *areaNameArray;

// 区域颜色数组
// |areaColorArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *areaColorArray;

// 头部信息
@property(nonatomic, readwrite) BOOL hasMatchInfo;
@property(nonatomic, readwrite, strong) PBMFootballHeader *matchInfo;

// 标题
@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

@end

#pragma mark - PBMFootIntegral_IntegralDetailInfo

typedef GPB_ENUM(PBMFootIntegral_IntegralDetailInfo_FieldNumber) {
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_Rank = 1,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_Team = 2,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_WinTimes = 3,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_TieTimes = 4,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_LoseTimes = 5,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_Point = 6,
  PBMFootIntegral_IntegralDetailInfo_FieldNumber_Color = 7,
};

@interface PBMFootIntegral_IntegralDetailInfo : GPBMessage

// 排名
@property(nonatomic, readwrite) BOOL hasRank;
@property(nonatomic, readwrite) int32_t rank;

// 球队
@property(nonatomic, readwrite) BOOL hasTeam;
@property(nonatomic, readwrite, copy) NSString *team;

// 胜次数
@property(nonatomic, readwrite) BOOL hasWinTimes;
@property(nonatomic, readwrite) int32_t winTimes;

// 平次数
@property(nonatomic, readwrite) BOOL hasTieTimes;
@property(nonatomic, readwrite) int32_t tieTimes;

// 负的次数
@property(nonatomic, readwrite) BOOL hasLoseTimes;
@property(nonatomic, readwrite) int32_t loseTimes;

// 积分
@property(nonatomic, readwrite) BOOL hasPoint;
@property(nonatomic, readwrite) int32_t point;

// 颜色
@property(nonatomic, readwrite) BOOL hasColor;
@property(nonatomic, readwrite, copy) NSString *color;

@end

#pragma mark - PBMFootComment

typedef GPB_ENUM(PBMFootComment_FieldNumber) {
  PBMFootComment_FieldNumber_MatchInfo = 1,
  PBMFootComment_FieldNumber_CommentArray = 2,
  PBMFootComment_FieldNumber_TotalNum = 3,
};

// 评论
@interface PBMFootComment : GPBMessage

//头部信息
@property(nonatomic, readwrite) BOOL hasMatchInfo;
@property(nonatomic, readwrite, strong) PBMFootballHeader *matchInfo;

//评论数组
// |commentArray| contains |PBMComment|
@property(nonatomic, readwrite, strong) NSMutableArray *commentArray;

// 总的评论数
@property(nonatomic, readwrite) BOOL hasTotalNum;
@property(nonatomic, readwrite) int32_t totalNum;

@end

#pragma mark - PBMFootOddsHandicap

typedef GPB_ENUM(PBMFootOddsHandicap_FieldNumber) {
  PBMFootOddsHandicap_FieldNumber_OupeiList = 1,
  PBMFootOddsHandicap_FieldNumber_YapanList = 2,
  PBMFootOddsHandicap_FieldNumber_DaXiaoqiuList = 3,
  PBMFootOddsHandicap_FieldNumber_BreakListArray = 4,
  PBMFootOddsHandicap_FieldNumber_MatchInfo = 5,
};

// 赔盘
@interface PBMFootOddsHandicap : GPBMessage

// 欧赔
@property(nonatomic, readwrite) BOOL hasOupeiList;
@property(nonatomic, readwrite, strong) PBMFootOddsHandicap_OddsHandItem *oupeiList;

// 亚盘
@property(nonatomic, readwrite) BOOL hasYapanList;
@property(nonatomic, readwrite, strong) PBMFootOddsHandicap_OddsHandItem *yapanList;

// 大小球
@property(nonatomic, readwrite) BOOL hasDaXiaoqiuList;
@property(nonatomic, readwrite, strong) PBMFootOddsHandicap_OddsHandItem *daXiaoqiuList;

// 盈亏
// |breakListArray| contains |PBMFootOddsHandicap_BreakInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *breakListArray;

// 头部信息
@property(nonatomic, readwrite) BOOL hasMatchInfo;
@property(nonatomic, readwrite, strong) PBMFootballHeader *matchInfo;

@end

#pragma mark - PBMFootOddsHandicap_OddsInfo

typedef GPB_ENUM(PBMFootOddsHandicap_OddsInfo_FieldNumber) {
  PBMFootOddsHandicap_OddsInfo_FieldNumber_CompanyName = 1,
  PBMFootOddsHandicap_OddsInfo_FieldNumber_InitOddsArray = 2,
  PBMFootOddsHandicap_OddsInfo_FieldNumber_CurrOddsArray = 3,
  PBMFootOddsHandicap_OddsInfo_FieldNumber_TrendListArray = 4,
};

@interface PBMFootOddsHandicap_OddsInfo : GPBMessage

// 公司名称
@property(nonatomic, readwrite) BOOL hasCompanyName;
@property(nonatomic, readwrite, copy) NSString *companyName;

// 初始赔率
// |initOddsArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *initOddsArray;
- (NSMutableArray *)initOddsArray GPB_METHOD_FAMILY_NONE;

// 最新赔率
// |currOddsArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *currOddsArray;

// 相对于初始值是增还是降1,0,-1 升，平，降
@property(nonatomic, readwrite, strong) GPBInt32Array *trendListArray;

@end

#pragma mark - PBMFootOddsHandicap_BreakInfo

typedef GPB_ENUM(PBMFootOddsHandicap_BreakInfo_FieldNumber) {
  PBMFootOddsHandicap_BreakInfo_FieldNumber_Title = 1,
  PBMFootOddsHandicap_BreakInfo_FieldNumber_Amount = 2,
  PBMFootOddsHandicap_BreakInfo_FieldNumber_Odds = 3,
  PBMFootOddsHandicap_BreakInfo_FieldNumber_Ratio = 4,
  PBMFootOddsHandicap_BreakInfo_FieldNumber_Breakeven = 5,
};

@interface PBMFootOddsHandicap_BreakInfo : GPBMessage

// 项目
@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

// 金额
@property(nonatomic, readwrite) BOOL hasAmount;
@property(nonatomic, readwrite, copy) NSString *amount;

// 赔率
@property(nonatomic, readwrite) BOOL hasOdds;
@property(nonatomic, readwrite, copy) NSString *odds;

// 比例
@property(nonatomic, readwrite) BOOL hasRatio;
@property(nonatomic, readwrite, copy) NSString *ratio;

// 庄家盈亏
@property(nonatomic, readwrite) BOOL hasBreakeven;
@property(nonatomic, readwrite, copy) NSString *breakeven;

@end

#pragma mark - PBMFootOddsHandicap_OddsHandItem

typedef GPB_ENUM(PBMFootOddsHandicap_OddsHandItem_FieldNumber) {
  PBMFootOddsHandicap_OddsHandItem_FieldNumber_OddsInfoListArray = 1,
  PBMFootOddsHandicap_OddsHandItem_FieldNumber_CompanyNameListArray = 2,
};

@interface PBMFootOddsHandicap_OddsHandItem : GPBMessage

// 欧赔列表
// |oddsInfoListArray| contains |PBMFootOddsHandicap_OddsInfo|
@property(nonatomic, readwrite, strong) NSMutableArray *oddsInfoListArray;

// 所有公司
// |companyNameListArray| contains |PBMCompanyItem|
@property(nonatomic, readwrite, strong) NSMutableArray *companyNameListArray;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
