// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: football_data_center.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "FootballDataCenter.pbobjc.h"
#import "Gamelive.pbobjc.h"
#import "BasketballDataCenter.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PBMFootballDataCenterRoot

@implementation PBMFootballDataCenterRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    registry = [[GPBExtensionRegistry alloc] init];
    static GPBExtensionDescription descriptions[] = {
    };
    #pragma unused (descriptions)
    [registry addExtensions:[PBMGameliveRoot extensionRegistry]];
    [registry addExtensions:[PBMBasketballDataCenterRoot extensionRegistry]];
  }
  return registry;
}

@end

static GPBFileDescriptor *PBMFootballDataCenterRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"Dacai.Protobuf"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBMFootballHeader

@implementation PBMFootballHeader

@dynamic hasHomeTeamIcon, homeTeamIcon;
@dynamic hasAwayTeamIcon, awayTeamIcon;
@dynamic hasHomeTeamName, homeTeamName;
@dynamic hasAwayTeamName, awayTeamName;
@dynamic hasHomeTeamRank, homeTeamRank;
@dynamic hasAwayTeamRank, awayTeamRank;
@dynamic hasStartTime, startTime;
@dynamic hasStatus, status;
@dynamic hasHomeScore, homeScore;
@dynamic hasAwayScore, awayScore;
@dynamic hasHomeHalfScore, homeHalfScore;
@dynamic hasAwayHalfScore, awayHalfScore;
@dynamic hasHalfStartTime, halfStartTime;
@dynamic hasFocus, focus;

typedef struct PBMFootballHeader_Storage {
  uint32_t _has_storage_[1];
  BOOL focus;
  PBMFootballMatchStatus status;
  int32_t homeScore;
  int32_t awayScore;
  int32_t homeHalfScore;
  int32_t awayHalfScore;
  NSString *homeTeamIcon;
  NSString *awayTeamIcon;
  NSString *homeTeamName;
  NSString *awayTeamName;
  NSString *homeTeamRank;
  NSString *awayTeamRank;
  NSString *startTime;
  NSString *halfStartTime;
} PBMFootballHeader_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "homeTeamIcon",
        .number = PBMFootballHeader_FieldNumber_HomeTeamIcon,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, homeTeamIcon),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayTeamIcon",
        .number = PBMFootballHeader_FieldNumber_AwayTeamIcon,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, awayTeamIcon),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeTeamName",
        .number = PBMFootballHeader_FieldNumber_HomeTeamName,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, homeTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayTeamName",
        .number = PBMFootballHeader_FieldNumber_AwayTeamName,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, awayTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeTeamRank",
        .number = PBMFootballHeader_FieldNumber_HomeTeamRank,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, homeTeamRank),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayTeamRank",
        .number = PBMFootballHeader_FieldNumber_AwayTeamRank,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, awayTeamRank),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "startTime",
        .number = PBMFootballHeader_FieldNumber_StartTime,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, startTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "status",
        .number = PBMFootballHeader_FieldNumber_Status,
        .hasIndex = 7,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .type = GPBTypeEnum,
        .offset = offsetof(PBMFootballHeader_Storage, status),
        .defaultValue.valueEnum = PBMFootballMatchStatus_FootballNotStart,
        .typeSpecific.enumDescFunc = PBMFootballMatchStatus_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "homeScore",
        .number = PBMFootballHeader_FieldNumber_HomeScore,
        .hasIndex = 8,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootballHeader_Storage, homeScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayScore",
        .number = PBMFootballHeader_FieldNumber_AwayScore,
        .hasIndex = 9,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootballHeader_Storage, awayScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeHalfScore",
        .number = PBMFootballHeader_FieldNumber_HomeHalfScore,
        .hasIndex = 10,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootballHeader_Storage, homeHalfScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayHalfScore",
        .number = PBMFootballHeader_FieldNumber_AwayHalfScore,
        .hasIndex = 11,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootballHeader_Storage, awayHalfScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "halfStartTime",
        .number = PBMFootballHeader_FieldNumber_HalfStartTime,
        .hasIndex = 12,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootballHeader_Storage, halfStartTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "focus",
        .number = PBMFootballHeader_FieldNumber_Focus,
        .hasIndex = 13,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMFootballHeader_Storage, focus),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootballHeader class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootballHeader_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootEventData

@implementation PBMFootEventData

@dynamic hasMatchInfo, matchInfo;
@dynamic eventListArray;
@dynamic skillListArray;
@dynamic homeListArray;
@dynamic awayListArray;

typedef struct PBMFootEventData_Storage {
  uint32_t _has_storage_[1];
  PBMFootballHeader *matchInfo;
  NSMutableArray *eventListArray;
  NSMutableArray *skillListArray;
  NSMutableArray *homeListArray;
  NSMutableArray *awayListArray;
} PBMFootEventData_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "matchInfo",
        .number = PBMFootEventData_FieldNumber_MatchInfo,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootEventData_Storage, matchInfo),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootballHeader),
        .fieldOptions = NULL,
      },
      {
        .name = "eventListArray",
        .number = PBMFootEventData_FieldNumber_EventListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootEventData_Storage, eventListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootEventData_MatchEventInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "skillListArray",
        .number = PBMFootEventData_FieldNumber_SkillListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootEventData_Storage, skillListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootEventData_SkillDetailInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "homeListArray",
        .number = PBMFootEventData_FieldNumber_HomeListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootEventData_Storage, homeListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootEventData_FormationDetailInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "awayListArray",
        .number = PBMFootEventData_FieldNumber_AwayListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootEventData_Storage, awayListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootEventData_FormationDetailInfo),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootEventData class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootEventData_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootEventData_MatchEventInfo

@implementation PBMFootEventData_MatchEventInfo

@dynamic hasHomeOrAway, homeOrAway;
@dynamic hasPlayer, player;
@dynamic hasTime, time;
@dynamic hasEvent, event;

typedef struct PBMFootEventData_MatchEventInfo_Storage {
  uint32_t _has_storage_[1];
  BOOL homeOrAway;
  int32_t time;
  PBMFootballEvent event;
  NSString *player;
} PBMFootEventData_MatchEventInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "homeOrAway",
        .number = PBMFootEventData_MatchEventInfo_FieldNumber_HomeOrAway,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMFootEventData_MatchEventInfo_Storage, homeOrAway),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "player",
        .number = PBMFootEventData_MatchEventInfo_FieldNumber_Player,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootEventData_MatchEventInfo_Storage, player),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "time",
        .number = PBMFootEventData_MatchEventInfo_FieldNumber_Time,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootEventData_MatchEventInfo_Storage, time),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "event",
        .number = PBMFootEventData_MatchEventInfo_FieldNumber_Event,
        .hasIndex = 3,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .type = GPBTypeEnum,
        .offset = offsetof(PBMFootEventData_MatchEventInfo_Storage, event),
        .defaultValue.valueEnum = PBMFootballEvent_Goals,
        .typeSpecific.enumDescFunc = PBMFootballEvent_EnumDescriptor,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootEventData_MatchEventInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootEventData_MatchEventInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootEventData_SkillDetailInfo

@implementation PBMFootEventData_SkillDetailInfo

@dynamic hasName, name;
@dynamic hasHomeCount, homeCount;
@dynamic hasAwayCount, awayCount;
@dynamic hasHomeText, homeText;
@dynamic hasAwayText, awayText;

typedef struct PBMFootEventData_SkillDetailInfo_Storage {
  uint32_t _has_storage_[1];
  int32_t homeCount;
  int32_t awayCount;
  NSString *name;
  NSString *homeText;
  NSString *awayText;
} PBMFootEventData_SkillDetailInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .number = PBMFootEventData_SkillDetailInfo_FieldNumber_Name,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootEventData_SkillDetailInfo_Storage, name),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeCount",
        .number = PBMFootEventData_SkillDetailInfo_FieldNumber_HomeCount,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootEventData_SkillDetailInfo_Storage, homeCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayCount",
        .number = PBMFootEventData_SkillDetailInfo_FieldNumber_AwayCount,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootEventData_SkillDetailInfo_Storage, awayCount),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeText",
        .number = PBMFootEventData_SkillDetailInfo_FieldNumber_HomeText,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootEventData_SkillDetailInfo_Storage, homeText),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayText",
        .number = PBMFootEventData_SkillDetailInfo_FieldNumber_AwayText,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootEventData_SkillDetailInfo_Storage, awayText),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootEventData_SkillDetailInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootEventData_SkillDetailInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootEventData_FormationDetailInfo

@implementation PBMFootEventData_FormationDetailInfo

@dynamic hasNumber, number;
@dynamic hasPlayer, player;
@dynamic hasFirstPlayer, firstPlayer;

typedef struct PBMFootEventData_FormationDetailInfo_Storage {
  uint32_t _has_storage_[1];
  BOOL firstPlayer;
  int32_t number;
  NSString *player;
} PBMFootEventData_FormationDetailInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "number",
        .number = PBMFootEventData_FormationDetailInfo_FieldNumber_Number,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootEventData_FormationDetailInfo_Storage, number),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "player",
        .number = PBMFootEventData_FormationDetailInfo_FieldNumber_Player,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootEventData_FormationDetailInfo_Storage, player),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "firstPlayer",
        .number = PBMFootEventData_FormationDetailInfo_FieldNumber_FirstPlayer,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeBool,
        .offset = offsetof(PBMFootEventData_FormationDetailInfo_Storage, firstPlayer),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\001\003\013\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootEventData_FormationDetailInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootEventData_FormationDetailInfo_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootAnalysis

@implementation PBMFootAnalysis

@dynamic hasHomeWinTimes, homeWinTimes;
@dynamic hasHistoryTieTimes, historyTieTimes;
@dynamic hasAwayWinTimes, awayWinTimes;
@dynamic homeRecentStatusArray;
@dynamic awayRecentStatusArray;
@dynamic hasHomeItem, homeItem;
@dynamic hasAwayItem, awayItem;
@dynamic hasMatchInfo, matchInfo;

typedef struct PBMFootAnalysis_Storage {
  uint32_t _has_storage_[1];
  int32_t homeWinTimes;
  int32_t historyTieTimes;
  int32_t awayWinTimes;
  GPBInt32Array *homeRecentStatusArray;
  GPBInt32Array *awayRecentStatusArray;
  PBMFootAnalysis_MatchFutureItem *homeItem;
  PBMFootAnalysis_MatchFutureItem *awayItem;
  PBMFootballHeader *matchInfo;
} PBMFootAnalysis_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "homeWinTimes",
        .number = PBMFootAnalysis_FieldNumber_HomeWinTimes,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysis_Storage, homeWinTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "historyTieTimes",
        .number = PBMFootAnalysis_FieldNumber_HistoryTieTimes,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysis_Storage, historyTieTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayWinTimes",
        .number = PBMFootAnalysis_FieldNumber_AwayWinTimes,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysis_Storage, awayWinTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeRecentStatusArray",
        .number = PBMFootAnalysis_FieldNumber_HomeRecentStatusArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysis_Storage, homeRecentStatusArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayRecentStatusArray",
        .number = PBMFootAnalysis_FieldNumber_AwayRecentStatusArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysis_Storage, awayRecentStatusArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeItem",
        .number = PBMFootAnalysis_FieldNumber_HomeItem,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysis_Storage, homeItem),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysis_MatchFutureItem),
        .fieldOptions = NULL,
      },
      {
        .name = "awayItem",
        .number = PBMFootAnalysis_FieldNumber_AwayItem,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysis_Storage, awayItem),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysis_MatchFutureItem),
        .fieldOptions = NULL,
      },
      {
        .name = "matchInfo",
        .number = PBMFootAnalysis_FieldNumber_MatchInfo,
        .hasIndex = 7,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysis_Storage, matchInfo),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootballHeader),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootAnalysis class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootAnalysis_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootAnalysis_MatchFutureItem

@implementation PBMFootAnalysis_MatchFutureItem

@dynamic hasStartTime, startTime;
@dynamic hasHomeTeamName, homeTeamName;
@dynamic hasAwayTeamName, awayTeamName;
@dynamic hasHomeIcon, homeIcon;
@dynamic hasAwayIcon, awayIcon;

typedef struct PBMFootAnalysis_MatchFutureItem_Storage {
  uint32_t _has_storage_[1];
  NSString *startTime;
  NSString *homeTeamName;
  NSString *awayTeamName;
  NSString *homeIcon;
  NSString *awayIcon;
} PBMFootAnalysis_MatchFutureItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "startTime",
        .number = PBMFootAnalysis_MatchFutureItem_FieldNumber_StartTime,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysis_MatchFutureItem_Storage, startTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeTeamName",
        .number = PBMFootAnalysis_MatchFutureItem_FieldNumber_HomeTeamName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysis_MatchFutureItem_Storage, homeTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayTeamName",
        .number = PBMFootAnalysis_MatchFutureItem_FieldNumber_AwayTeamName,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysis_MatchFutureItem_Storage, awayTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeIcon",
        .number = PBMFootAnalysis_MatchFutureItem_FieldNumber_HomeIcon,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysis_MatchFutureItem_Storage, homeIcon),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayIcon",
        .number = PBMFootAnalysis_MatchFutureItem_FieldNumber_AwayIcon,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysis_MatchFutureItem_Storage, awayIcon),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootAnalysis_MatchFutureItem class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootAnalysis_MatchFutureItem_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootAnalysisDetail

@implementation PBMFootAnalysisDetail

@dynamic hasHomeHistory, homeHistory;
@dynamic hasHomeRecent, homeRecent;
@dynamic hasAwayRecent, awayRecent;
@dynamic hasHomeFuture, homeFuture;
@dynamic hasAwayFuture, awayFuture;

typedef struct PBMFootAnalysisDetail_Storage {
  uint32_t _has_storage_[1];
  PBMFootAnalysisDetail_MatchInfoTitle *homeHistory;
  PBMFootAnalysisDetail_MatchInfoTitle *homeRecent;
  PBMFootAnalysisDetail_MatchInfoTitle *awayRecent;
  PBMFootAnalysisDetail_MatchInfoTitle *homeFuture;
  PBMFootAnalysisDetail_MatchInfoTitle *awayFuture;
} PBMFootAnalysisDetail_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "homeHistory",
        .number = PBMFootAnalysisDetail_FieldNumber_HomeHistory,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_Storage, homeHistory),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoTitle),
        .fieldOptions = NULL,
      },
      {
        .name = "homeRecent",
        .number = PBMFootAnalysisDetail_FieldNumber_HomeRecent,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_Storage, homeRecent),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoTitle),
        .fieldOptions = NULL,
      },
      {
        .name = "awayRecent",
        .number = PBMFootAnalysisDetail_FieldNumber_AwayRecent,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_Storage, awayRecent),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoTitle),
        .fieldOptions = NULL,
      },
      {
        .name = "homeFuture",
        .number = PBMFootAnalysisDetail_FieldNumber_HomeFuture,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_Storage, homeFuture),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoTitle),
        .fieldOptions = NULL,
      },
      {
        .name = "awayFuture",
        .number = PBMFootAnalysisDetail_FieldNumber_AwayFuture,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_Storage, awayFuture),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoTitle),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootAnalysisDetail class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootAnalysisDetail_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootAnalysisDetail_MatchInfoTitle

@implementation PBMFootAnalysisDetail_MatchInfoTitle

@dynamic hasTotalWin, totalWin;
@dynamic hasTotalTie, totalTie;
@dynamic hasTotalLose, totalLose;
@dynamic hasHomeWinTimes, homeWinTimes;
@dynamic hasHomeTieTimes, homeTieTimes;
@dynamic hasHomeLoseTimes, homeLoseTimes;
@dynamic matchInfoListArray;

typedef struct PBMFootAnalysisDetail_MatchInfoTitle_Storage {
  uint32_t _has_storage_[1];
  int32_t totalWin;
  int32_t totalTie;
  int32_t totalLose;
  int32_t homeWinTimes;
  int32_t homeTieTimes;
  int32_t homeLoseTimes;
  NSMutableArray *matchInfoListArray;
} PBMFootAnalysisDetail_MatchInfoTitle_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "totalWin",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalWin,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, totalWin),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "totalTie",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalTie,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, totalTie),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "totalLose",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_TotalLose,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, totalLose),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeWinTimes",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeWinTimes,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, homeWinTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeTieTimes",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeTieTimes,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, homeTieTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeLoseTimes",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_HomeLoseTimes,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, homeLoseTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "matchInfoListArray",
        .number = PBMFootAnalysisDetail_MatchInfoTitle_FieldNumber_MatchInfoListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoTitle_Storage, matchInfoListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootAnalysisDetail_MatchInfoDetailInfo),
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootAnalysisDetail_MatchInfoTitle class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootAnalysisDetail_MatchInfoTitle_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootAnalysisDetail_MatchInfoDetailInfo

@implementation PBMFootAnalysisDetail_MatchInfoDetailInfo

@dynamic hasCompletion, completion;
@dynamic hasStartTime, startTime;
@dynamic hasHomeTeamName, homeTeamName;
@dynamic hasAwayTeamName, awayTeamName;
@dynamic hasHomeScore, homeScore;
@dynamic hasAwayScore, awayScore;

typedef struct PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage {
  uint32_t _has_storage_[1];
  int32_t homeScore;
  int32_t awayScore;
  NSString *completion;
  NSString *startTime;
  NSString *homeTeamName;
  NSString *awayTeamName;
} PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "completion",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_Completion,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, completion),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "startTime",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_StartTime,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, startTime),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeTeamName",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_HomeTeamName,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, homeTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayTeamName",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_AwayTeamName,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, awayTeamName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "homeScore",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_HomeScore,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, homeScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "awayScore",
        .number = PBMFootAnalysisDetail_MatchInfoDetailInfo_FieldNumber_AwayScore,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage, awayScore),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootAnalysisDetail_MatchInfoDetailInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootAnalysisDetail_MatchInfoDetailInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootIntegral

@implementation PBMFootIntegral

@dynamic integralListArray;
@dynamic areaNameArray;
@dynamic areaColorArray;
@dynamic hasMatchInfo, matchInfo;
@dynamic hasTitle, title;

typedef struct PBMFootIntegral_Storage {
  uint32_t _has_storage_[1];
  NSMutableArray *integralListArray;
  NSMutableArray *areaNameArray;
  NSMutableArray *areaColorArray;
  PBMFootballHeader *matchInfo;
  NSString *title;
} PBMFootIntegral_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "integralListArray",
        .number = PBMFootIntegral_FieldNumber_IntegralListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootIntegral_Storage, integralListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootIntegral_IntegralDetailInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "areaNameArray",
        .number = PBMFootIntegral_FieldNumber_AreaNameArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootIntegral_Storage, areaNameArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "areaColorArray",
        .number = PBMFootIntegral_FieldNumber_AreaColorArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootIntegral_Storage, areaColorArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "matchInfo",
        .number = PBMFootIntegral_FieldNumber_MatchInfo,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootIntegral_Storage, matchInfo),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootballHeader),
        .fieldOptions = NULL,
      },
      {
        .name = "title",
        .number = PBMFootIntegral_FieldNumber_Title,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootIntegral_Storage, title),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\003\001\000Integral_list\000\002\000areaName\000\003\000areaColor\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootIntegral class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootIntegral_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootIntegral_IntegralDetailInfo

@implementation PBMFootIntegral_IntegralDetailInfo

@dynamic hasRank, rank;
@dynamic hasTeam, team;
@dynamic hasWinTimes, winTimes;
@dynamic hasTieTimes, tieTimes;
@dynamic hasLoseTimes, loseTimes;
@dynamic hasPoint, point;
@dynamic hasColor, color;

typedef struct PBMFootIntegral_IntegralDetailInfo_Storage {
  uint32_t _has_storage_[1];
  int32_t rank;
  int32_t winTimes;
  int32_t tieTimes;
  int32_t loseTimes;
  int32_t point;
  NSString *team;
  NSString *color;
} PBMFootIntegral_IntegralDetailInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rank",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_Rank,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, rank),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "team",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_Team,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, team),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "winTimes",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_WinTimes,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, winTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "tieTimes",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_TieTimes,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, tieTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "loseTimes",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_LoseTimes,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, loseTimes),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "point",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_Point,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, point),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "color",
        .number = PBMFootIntegral_IntegralDetailInfo_FieldNumber_Color,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootIntegral_IntegralDetailInfo_Storage, color),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootIntegral_IntegralDetailInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootIntegral_IntegralDetailInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootComment

@implementation PBMFootComment

@dynamic hasMatchInfo, matchInfo;
@dynamic commentArray;
@dynamic hasTotalNum, totalNum;

typedef struct PBMFootComment_Storage {
  uint32_t _has_storage_[1];
  int32_t totalNum;
  PBMFootballHeader *matchInfo;
  NSMutableArray *commentArray;
} PBMFootComment_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "matchInfo",
        .number = PBMFootComment_FieldNumber_MatchInfo,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootComment_Storage, matchInfo),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootballHeader),
        .fieldOptions = NULL,
      },
      {
        .name = "commentArray",
        .number = PBMFootComment_FieldNumber_CommentArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootComment_Storage, commentArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMComment),
        .fieldOptions = NULL,
      },
      {
        .name = "totalNum",
        .number = PBMFootComment_FieldNumber_TotalNum,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootComment_Storage, totalNum),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootComment class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootComment_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootOddsHandicap

@implementation PBMFootOddsHandicap

@dynamic hasOupeiList, oupeiList;
@dynamic hasYapanList, yapanList;
@dynamic hasDaXiaoqiuList, daXiaoqiuList;
@dynamic breakListArray;
@dynamic hasMatchInfo, matchInfo;

typedef struct PBMFootOddsHandicap_Storage {
  uint32_t _has_storage_[1];
  PBMFootOddsHandicap_OddsHandItem *oupeiList;
  PBMFootOddsHandicap_OddsHandItem *yapanList;
  PBMFootOddsHandicap_OddsHandItem *daXiaoqiuList;
  NSMutableArray *breakListArray;
  PBMFootballHeader *matchInfo;
} PBMFootOddsHandicap_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "oupeiList",
        .number = PBMFootOddsHandicap_FieldNumber_OupeiList,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_Storage, oupeiList),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootOddsHandicap_OddsHandItem),
        .fieldOptions = NULL,
      },
      {
        .name = "yapanList",
        .number = PBMFootOddsHandicap_FieldNumber_YapanList,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_Storage, yapanList),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootOddsHandicap_OddsHandItem),
        .fieldOptions = NULL,
      },
      {
        .name = "daXiaoqiuList",
        .number = PBMFootOddsHandicap_FieldNumber_DaXiaoqiuList,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_Storage, daXiaoqiuList),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootOddsHandicap_OddsHandItem),
        .fieldOptions = NULL,
      },
      {
        .name = "breakListArray",
        .number = PBMFootOddsHandicap_FieldNumber_BreakListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_Storage, breakListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootOddsHandicap_BreakInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "matchInfo",
        .number = PBMFootOddsHandicap_FieldNumber_MatchInfo,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_Storage, matchInfo),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootballHeader),
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\001\003\t\244\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootOddsHandicap class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootOddsHandicap_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootOddsHandicap_OddsInfo

@implementation PBMFootOddsHandicap_OddsInfo

@dynamic hasCompanyName, companyName;
@dynamic initOddsArray;
@dynamic currOddsArray;
@dynamic trendListArray;

typedef struct PBMFootOddsHandicap_OddsInfo_Storage {
  uint32_t _has_storage_[1];
  NSString *companyName;
  NSMutableArray *initOddsArray;
  NSMutableArray *currOddsArray;
  GPBInt32Array *trendListArray;
} PBMFootOddsHandicap_OddsInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "companyName",
        .number = PBMFootOddsHandicap_OddsInfo_FieldNumber_CompanyName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_OddsInfo_Storage, companyName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "initOddsArray",
        .number = PBMFootOddsHandicap_OddsInfo_FieldNumber_InitOddsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_OddsInfo_Storage, initOddsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "currOddsArray",
        .number = PBMFootOddsHandicap_OddsInfo_FieldNumber_CurrOddsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_OddsInfo_Storage, currOddsArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "trendListArray",
        .number = PBMFootOddsHandicap_OddsInfo_FieldNumber_TrendListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMFootOddsHandicap_OddsInfo_Storage, trendListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootOddsHandicap_OddsInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootOddsHandicap_OddsInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootOddsHandicap_BreakInfo

@implementation PBMFootOddsHandicap_BreakInfo

@dynamic hasTitle, title;
@dynamic hasAmount, amount;
@dynamic hasOdds, odds;
@dynamic hasRatio, ratio;
@dynamic hasBreakeven, breakeven;

typedef struct PBMFootOddsHandicap_BreakInfo_Storage {
  uint32_t _has_storage_[1];
  NSString *title;
  NSString *amount;
  NSString *odds;
  NSString *ratio;
  NSString *breakeven;
} PBMFootOddsHandicap_BreakInfo_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "title",
        .number = PBMFootOddsHandicap_BreakInfo_FieldNumber_Title,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_BreakInfo_Storage, title),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "amount",
        .number = PBMFootOddsHandicap_BreakInfo_FieldNumber_Amount,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_BreakInfo_Storage, amount),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "odds",
        .number = PBMFootOddsHandicap_BreakInfo_FieldNumber_Odds,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_BreakInfo_Storage, odds),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "ratio",
        .number = PBMFootOddsHandicap_BreakInfo_FieldNumber_Ratio,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_BreakInfo_Storage, ratio),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "breakeven",
        .number = PBMFootOddsHandicap_BreakInfo_FieldNumber_Breakeven,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFootOddsHandicap_BreakInfo_Storage, breakeven),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootOddsHandicap_BreakInfo class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootOddsHandicap_BreakInfo_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFootOddsHandicap_OddsHandItem

@implementation PBMFootOddsHandicap_OddsHandItem

@dynamic oddsInfoListArray;
@dynamic companyNameListArray;

typedef struct PBMFootOddsHandicap_OddsHandItem_Storage {
  uint32_t _has_storage_[1];
  NSMutableArray *oddsInfoListArray;
  NSMutableArray *companyNameListArray;
} PBMFootOddsHandicap_OddsHandItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "oddsInfoListArray",
        .number = PBMFootOddsHandicap_OddsHandItem_FieldNumber_OddsInfoListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_OddsHandItem_Storage, oddsInfoListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMFootOddsHandicap_OddsInfo),
        .fieldOptions = NULL,
      },
      {
        .name = "companyNameListArray",
        .number = PBMFootOddsHandicap_OddsHandItem_FieldNumber_CompanyNameListArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMFootOddsHandicap_OddsHandItem_Storage, companyNameListArray),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMCompanyItem),
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\002\001\000oddsInfo_list\000\002\000companyName_list\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFootOddsHandicap_OddsHandItem class]
                                              rootClass:[PBMFootballDataCenterRoot class]
                                                   file:PBMFootballDataCenterRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFootOddsHandicap_OddsHandItem_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
