// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remind.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - PBMRemindRoot

@interface PBMRemindRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PBMRemindResult

typedef GPB_ENUM(PBMRemindResult_FieldNumber) {
  PBMRemindResult_FieldNumber_SaleStop = 1,
  PBMRemindResult_FieldNumber_GameType = 2,
  PBMRemindResult_FieldNumber_NightStopTicket = 3,
  PBMRemindResult_FieldNumber_GameNameNew = 4,
  PBMRemindResult_FieldNumber_GameId = 5,
  PBMRemindResult_FieldNumber_GameNameStop = 6,
  PBMRemindResult_FieldNumber_DrawTime = 7,
};

//提醒接口返回
@interface PBMRemindResult : GPBMessage

//是否停售
@property(nonatomic, readwrite) BOOL hasSaleStop;
@property(nonatomic, readwrite) BOOL saleStop;

//停售彩种类别
@property(nonatomic, readwrite) BOOL hasGameType;
@property(nonatomic, readwrite) int32_t gameType;

//是否夜间停止出票
@property(nonatomic, readwrite) BOOL hasNightStopTicket;
@property(nonatomic, readwrite) BOOL nightStopTicket;

//新期号
@property(nonatomic, readwrite) BOOL hasGameNameNew;
@property(nonatomic, readwrite, copy) NSString *gameNameNew;

//新期主键id
@property(nonatomic, readwrite) BOOL hasGameId;
@property(nonatomic, readwrite) int32_t gameId;

//当前期是否截止
@property(nonatomic, readwrite) BOOL hasGameNameStop;
@property(nonatomic, readwrite) BOOL gameNameStop;

//开奖时间
@property(nonatomic, readwrite) BOOL hasDrawTime;
@property(nonatomic, readwrite, copy) NSString *drawTime;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
