// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Security.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PBMSecurityRoot

@implementation PBMSecurityRoot

@end

static GPBFileDescriptor *PBMSecurityRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"Dacai.Protobuf"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBMSecurityHome

@implementation PBMSecurityHome

@dynamic hasNameItem, nameItem;
@dynamic hasBankItem, bankItem;
@dynamic hasShowAccount, showAccount;
@dynamic hasShowPhone, showPhone;
@dynamic hasShowLoginPassword, showLoginPassword;
@dynamic hasShowPayPassword, showPayPassword;
@dynamic hasPhoneNumber, phoneNumber;

typedef struct PBMSecurityHome_Storage {
  uint32_t _has_storage_[1];
  BOOL showAccount;
  BOOL showPhone;
  BOOL showLoginPassword;
  BOOL showPayPassword;
  PBMSecurityHome_RealNameItem *nameItem;
  PBMSecurityHome_BankInfoItem *bankItem;
  NSString *phoneNumber;
} PBMSecurityHome_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "nameItem",
        .number = PBMSecurityHome_FieldNumber_NameItem,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMSecurityHome_Storage, nameItem),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMSecurityHome_RealNameItem),
        .fieldOptions = NULL,
      },
      {
        .name = "bankItem",
        .number = PBMSecurityHome_FieldNumber_BankItem,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeMessage,
        .offset = offsetof(PBMSecurityHome_Storage, bankItem),
        .defaultValue.valueMessage = nil,
        .typeSpecific.className = GPBStringifySymbol(PBMSecurityHome_BankInfoItem),
        .fieldOptions = NULL,
      },
      {
        .name = "showAccount",
        .number = PBMSecurityHome_FieldNumber_ShowAccount,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMSecurityHome_Storage, showAccount),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "showPhone",
        .number = PBMSecurityHome_FieldNumber_ShowPhone,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMSecurityHome_Storage, showPhone),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "showLoginPassword",
        .number = PBMSecurityHome_FieldNumber_ShowLoginPassword,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMSecurityHome_Storage, showLoginPassword),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "showPayPassword",
        .number = PBMSecurityHome_FieldNumber_ShowPayPassword,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeBool,
        .offset = offsetof(PBMSecurityHome_Storage, showPayPassword),
        .defaultValue.valueBool = NO,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "phoneNumber",
        .number = PBMSecurityHome_FieldNumber_PhoneNumber,
        .hasIndex = 6,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMSecurityHome class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMSecurityHome_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMSecurityHome_RealNameItem

@implementation PBMSecurityHome_RealNameItem

@dynamic hasRealName, realName;
@dynamic hasCardId, cardId;

typedef struct PBMSecurityHome_RealNameItem_Storage {
  uint32_t _has_storage_[1];
  NSString *realName;
  NSString *cardId;
} PBMSecurityHome_RealNameItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "realName",
        .number = PBMSecurityHome_RealNameItem_FieldNumber_RealName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_RealNameItem_Storage, realName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "cardId",
        .number = PBMSecurityHome_RealNameItem_FieldNumber_CardId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_RealNameItem_Storage, cardId),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMSecurityHome_RealNameItem class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMSecurityHome_RealNameItem_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMSecurityHome_BankInfoItem

@implementation PBMSecurityHome_BankInfoItem

@dynamic hasBankName, bankName;
@dynamic hasBankNumber, bankNumber;
@dynamic hasBankAddress, bankAddress;

typedef struct PBMSecurityHome_BankInfoItem_Storage {
  uint32_t _has_storage_[1];
  NSString *bankName;
  NSString *bankNumber;
  NSString *bankAddress;
} PBMSecurityHome_BankInfoItem_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "bankName",
        .number = PBMSecurityHome_BankInfoItem_FieldNumber_BankName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_BankInfoItem_Storage, bankName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "bankNumber",
        .number = PBMSecurityHome_BankInfoItem_FieldNumber_BankNumber,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_BankInfoItem_Storage, bankNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "bankAddress",
        .number = PBMSecurityHome_BankInfoItem_FieldNumber_BankAddress,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSecurityHome_BankInfoItem_Storage, bankAddress),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMSecurityHome_BankInfoItem class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMSecurityHome_BankInfoItem_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMPhoneVerCodeRes

@implementation PBMPhoneVerCodeRes

@dynamic hasPhoneNumber, phoneNumber;

typedef struct PBMPhoneVerCodeRes_Storage {
  uint32_t _has_storage_[1];
  NSString *phoneNumber;
} PBMPhoneVerCodeRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phoneNumber",
        .number = PBMPhoneVerCodeRes_FieldNumber_PhoneNumber,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneVerCodeRes_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMPhoneVerCodeRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMPhoneVerCodeRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMPhoneBindingRes

@implementation PBMPhoneBindingRes

@dynamic hasPhoneNumber, phoneNumber;
@dynamic hasVerCode, verCode;
@dynamic hasToken, token;
@dynamic hasThirdLoginItem, thirdLoginItem;

typedef struct PBMPhoneBindingRes_Storage {
  uint32_t _has_storage_[1];
  NSString *phoneNumber;
  NSString *verCode;
  NSString *token;
  NSString *thirdLoginItem;
} PBMPhoneBindingRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phoneNumber",
        .number = PBMPhoneBindingRes_FieldNumber_PhoneNumber,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "verCode",
        .number = PBMPhoneBindingRes_FieldNumber_VerCode,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_Storage, verCode),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "token",
        .number = PBMPhoneBindingRes_FieldNumber_Token,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_Storage, token),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "thirdLoginItem",
        .number = PBMPhoneBindingRes_FieldNumber_ThirdLoginItem,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_Storage, thirdLoginItem),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMPhoneBindingRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMPhoneBindingRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMPhoneBindingRes_ThirdLogOnParam

@implementation PBMPhoneBindingRes_ThirdLogOnParam

@dynamic hasAppid, appid;
@dynamic hasAccessToken, accessToken;
@dynamic hasOpenid, openid;
@dynamic hasType, type;

typedef struct PBMPhoneBindingRes_ThirdLogOnParam_Storage {
  uint32_t _has_storage_[1];
  int32_t type;
  NSString *appid;
  NSString *accessToken;
  NSString *openid;
} PBMPhoneBindingRes_ThirdLogOnParam_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "appid",
        .number = PBMPhoneBindingRes_ThirdLogOnParam_FieldNumber_Appid,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_ThirdLogOnParam_Storage, appid),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "accessToken",
        .number = PBMPhoneBindingRes_ThirdLogOnParam_FieldNumber_AccessToken,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_ThirdLogOnParam_Storage, accessToken),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "openid",
        .number = PBMPhoneBindingRes_ThirdLogOnParam_FieldNumber_Openid,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneBindingRes_ThirdLogOnParam_Storage, openid),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "type",
        .number = PBMPhoneBindingRes_ThirdLogOnParam_FieldNumber_Type,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeInt32,
        .offset = offsetof(PBMPhoneBindingRes_ThirdLogOnParam_Storage, type),
        .defaultValue.valueInt32 = 0,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMPhoneBindingRes_ThirdLogOnParam class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMPhoneBindingRes_ThirdLogOnParam_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMGetTokenRes

@implementation PBMGetTokenRes

@dynamic hasToken, token;

typedef struct PBMGetTokenRes_Storage {
  uint32_t _has_storage_[1];
  NSString *token;
} PBMGetTokenRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "token",
        .number = PBMGetTokenRes_FieldNumber_Token,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMGetTokenRes_Storage, token),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMGetTokenRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMGetTokenRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMNewPhoneVerCodeRes

@implementation PBMNewPhoneVerCodeRes

@dynamic hasPhoneNumber, phoneNumber;
@dynamic hasToken, token;

typedef struct PBMNewPhoneVerCodeRes_Storage {
  uint32_t _has_storage_[1];
  NSString *phoneNumber;
  NSString *token;
} PBMNewPhoneVerCodeRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "phoneNumber",
        .number = PBMNewPhoneVerCodeRes_FieldNumber_PhoneNumber,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMNewPhoneVerCodeRes_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "token",
        .number = PBMNewPhoneVerCodeRes_FieldNumber_Token,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMNewPhoneVerCodeRes_Storage, token),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMNewPhoneVerCodeRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMNewPhoneVerCodeRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMPhoneLoseRes

@implementation PBMPhoneLoseRes

@dynamic hasAceName, aceName;
@dynamic hasCardNumber, cardNumber;
@dynamic hasBankNumber, bankNumber;

typedef struct PBMPhoneLoseRes_Storage {
  uint32_t _has_storage_[1];
  NSString *aceName;
  NSString *cardNumber;
  NSString *bankNumber;
} PBMPhoneLoseRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "aceName",
        .number = PBMPhoneLoseRes_FieldNumber_AceName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneLoseRes_Storage, aceName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "cardNumber",
        .number = PBMPhoneLoseRes_FieldNumber_CardNumber,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneLoseRes_Storage, cardNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "bankNumber",
        .number = PBMPhoneLoseRes_FieldNumber_BankNumber,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMPhoneLoseRes_Storage, bankNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMPhoneLoseRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMPhoneLoseRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMChangePassWordRes

@implementation PBMChangePassWordRes

@dynamic hasOldPassword, oldPassword;
@dynamic hasNewPassword, newPassword;

typedef struct PBMChangePassWordRes_Storage {
  uint32_t _has_storage_[1];
  NSString *oldPassword;
  NSString *newPassword;
} PBMChangePassWordRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "oldPassword",
        .number = PBMChangePassWordRes_FieldNumber_OldPassword,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChangePassWordRes_Storage, oldPassword),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "newPassword",
        .number = PBMChangePassWordRes_FieldNumber_NewPassword,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMChangePassWordRes_Storage, newPassword),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMChangePassWordRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMChangePassWordRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFindPassWordRes

@implementation PBMFindPassWordRes

@dynamic hasAceName, aceName;
@dynamic hasCardId, cardId;
@dynamic hasPhoneNumber, phoneNumber;
@dynamic hasVerCode, verCode;

typedef struct PBMFindPassWordRes_Storage {
  uint32_t _has_storage_[1];
  NSString *aceName;
  NSString *cardId;
  NSString *phoneNumber;
  NSString *verCode;
} PBMFindPassWordRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "aceName",
        .number = PBMFindPassWordRes_FieldNumber_AceName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindPassWordRes_Storage, aceName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "cardId",
        .number = PBMFindPassWordRes_FieldNumber_CardId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindPassWordRes_Storage, cardId),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "phoneNumber",
        .number = PBMFindPassWordRes_FieldNumber_PhoneNumber,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindPassWordRes_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "verCode",
        .number = PBMFindPassWordRes_FieldNumber_VerCode,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindPassWordRes_Storage, verCode),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFindPassWordRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFindPassWordRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMSetPassWordRes

@implementation PBMSetPassWordRes

@dynamic hasPassword, password;

typedef struct PBMSetPassWordRes_Storage {
  uint32_t _has_storage_[1];
  NSString *password;
} PBMSetPassWordRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "password",
        .number = PBMSetPassWordRes_FieldNumber_Password,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMSetPassWordRes_Storage, password),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMSetPassWordRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMSetPassWordRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMFindToSetPassWordRes

@implementation PBMFindToSetPassWordRes

@dynamic hasPassword, password;
@dynamic hasPhoneNumber, phoneNumber;
@dynamic hasToken, token;

typedef struct PBMFindToSetPassWordRes_Storage {
  uint32_t _has_storage_[1];
  NSString *password;
  NSString *phoneNumber;
  NSString *token;
} PBMFindToSetPassWordRes_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "password",
        .number = PBMFindToSetPassWordRes_FieldNumber_Password,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindToSetPassWordRes_Storage, password),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "phoneNumber",
        .number = PBMFindToSetPassWordRes_FieldNumber_PhoneNumber,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindToSetPassWordRes_Storage, phoneNumber),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "token",
        .number = PBMFindToSetPassWordRes_FieldNumber_Token,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMFindToSetPassWordRes_Storage, token),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMFindToSetPassWordRes class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMFindToSetPassWordRes_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMLoginOutAcoount

@implementation PBMLoginOutAcoount

@dynamic hasNoBetTotal, noBetTotal;
@dynamic hasUserMoney, userMoney;

typedef struct PBMLoginOutAcoount_Storage {
  uint32_t _has_storage_[1];
  NSString *noBetTotal;
  NSString *userMoney;
} PBMLoginOutAcoount_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "noBetTotal",
        .number = PBMLoginOutAcoount_FieldNumber_NoBetTotal,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMLoginOutAcoount_Storage, noBetTotal),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "userMoney",
        .number = PBMLoginOutAcoount_FieldNumber_UserMoney,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMLoginOutAcoount_Storage, userMoney),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMLoginOutAcoount class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMLoginOutAcoount_Storage)
                                             wireFormat:NO];
  }
  return descriptor;
}

@end

#pragma mark - PBMModifyDrawingCard

@implementation PBMModifyDrawingCard

@dynamic hasBankNo, bankNo;
@dynamic hasBankName, bankName;
@dynamic hasBankId, bankId;
@dynamic hasBlongToCity, blongToCity;
@dynamic hasToken, token;
@dynamic hasAttributionDesc, attributionDesc;

typedef struct PBMModifyDrawingCard_Storage {
  uint32_t _has_storage_[1];
  NSString *bankNo;
  NSString *bankName;
  NSString *bankId;
  NSString *token;
  NSString *attributionDesc;
  int64_t blongToCity;
} PBMModifyDrawingCard_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "bankNo",
        .number = PBMModifyDrawingCard_FieldNumber_BankNo,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMModifyDrawingCard_Storage, bankNo),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "bankName",
        .number = PBMModifyDrawingCard_FieldNumber_BankName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMModifyDrawingCard_Storage, bankName),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "bankId",
        .number = PBMModifyDrawingCard_FieldNumber_BankId,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMModifyDrawingCard_Storage, bankId),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "blongToCity",
        .number = PBMModifyDrawingCard_FieldNumber_BlongToCity,
        .hasIndex = 3,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .type = GPBTypeInt64,
        .offset = offsetof(PBMModifyDrawingCard_Storage, blongToCity),
        .defaultValue.valueInt64 = 0LL,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "token",
        .number = PBMModifyDrawingCard_FieldNumber_Token,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMModifyDrawingCard_Storage, token),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "attributionDesc",
        .number = PBMModifyDrawingCard_FieldNumber_AttributionDesc,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBMModifyDrawingCard_Storage, attributionDesc),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\001\004K\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBMModifyDrawingCard class]
                                              rootClass:[PBMSecurityRoot class]
                                                   file:PBMSecurityRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBMModifyDrawingCard_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
