// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wages.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Match;
@class User;

#pragma mark - Enum CreateWagesInput_DeclareTypeEnume

typedef GPB_ENUM(CreateWagesInput_DeclareTypeEnume) {
  //j激进
  CreateWagesInput_DeclareTypeEnume_Radical = 1,

  //稳健
  CreateWagesInput_DeclareTypeEnume_Solid = 2,
};

GPBEnumDescriptor *CreateWagesInput_DeclareTypeEnume_EnumDescriptor(void);

BOOL CreateWagesInput_DeclareTypeEnume_IsValidValue(int32_t value);


#pragma mark - WagesRoot

@interface WagesRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - WagesHome

typedef GPB_ENUM(WagesHome_FieldNumber) {
  WagesHome_FieldNumber_FansCount = 1,
  WagesHome_FieldNumber_Profit = 2,
  WagesHome_FieldNumber_WagesItemsArray = 3,
  WagesHome_FieldNumber_BackgroudImg = 4,
  WagesHome_FieldNumber_WagesCount = 5,
};

//心水首页
@interface WagesHome : GPBMessage

// 人气第一人数
@property(nonatomic, readwrite) BOOL hasFansCount;
@property(nonatomic, readwrite) int32_t fansCount;

// 赚钱第一数量
@property(nonatomic, readwrite) BOOL hasProfit;
@property(nonatomic, readwrite, copy) NSString *profit;

// 心水列表
// |wagesItemsArray| contains |Wages|
@property(nonatomic, readwrite, strong) NSMutableArray *wagesItemsArray;

// 背景图片	
@property(nonatomic, readwrite) BOOL hasBackgroudImg;
@property(nonatomic, readwrite, copy) NSString *backgroudImg;

// 心水总数
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int64_t wagesCount;

@end

#pragma mark - MyWages

typedef GPB_ENUM(MyWages_FieldNumber) {
  MyWages_FieldNumber_UserInfo = 1,
  MyWages_FieldNumber_WagesItemsArray = 2,
  MyWages_FieldNumber_WagesCount = 3,
};

@interface MyWages : GPBMessage

//用户信息  
@property(nonatomic, readwrite) BOOL hasUserInfo;
@property(nonatomic, readwrite, strong) User *userInfo;

//心水
// |wagesItemsArray| contains |Wages|
@property(nonatomic, readwrite, strong) NSMutableArray *wagesItemsArray;

//心水总数
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int64_t wagesCount;

@end

#pragma mark - MyFollow

typedef GPB_ENUM(MyFollow_FieldNumber) {
  MyFollow_FieldNumber_UserInfo = 1,
  MyFollow_FieldNumber_FollowUsersArray = 2,
  MyFollow_FieldNumber_FollowUserCount = 3,
};

//我的关注
@interface MyFollow : GPBMessage

//用户信息  
@property(nonatomic, readwrite) BOOL hasUserInfo;
@property(nonatomic, readwrite, strong) User *userInfo;

//关注人
// |followUsersArray| contains |User|
@property(nonatomic, readwrite, strong) NSMutableArray *followUsersArray;

//关注总人数 
@property(nonatomic, readwrite) BOOL hasFollowUserCount;
@property(nonatomic, readwrite) int32_t followUserCount;

@end

#pragma mark - WagesDetail

typedef GPB_ENUM(WagesDetail_FieldNumber) {
  WagesDetail_FieldNumber_UserInfo = 1,
  WagesDetail_FieldNumber_IsFocusedCreateUser = 2,
  WagesDetail_FieldNumber_WinAmount = 3,
  WagesDetail_FieldNumber_RecommandAttitude = 4,
  WagesDetail_FieldNumber_RecommandReason = 5,
  WagesDetail_FieldNumber_IsFree = 6,
  WagesDetail_FieldNumber_Price = 7,
  WagesDetail_FieldNumber_SellCount = 8,
  WagesDetail_FieldNumber_IsBuy = 9,
  WagesDetail_FieldNumber_BetItemsArray = 10,
};

//心水详情
@interface WagesDetail : GPBMessage

// 发起人
@property(nonatomic, readwrite) BOOL hasUserInfo;
@property(nonatomic, readwrite, strong) User *userInfo;

// 是否已经关注发起人
@property(nonatomic, readwrite) BOOL hasIsFocusedCreateUser;
@property(nonatomic, readwrite) BOOL isFocusedCreateUser;

// 预计奖金
@property(nonatomic, readwrite) BOOL hasWinAmount;
@property(nonatomic, readwrite, copy) NSString *winAmount;

// 推荐态度
@property(nonatomic, readwrite) BOOL hasRecommandAttitude;
@property(nonatomic, readwrite, copy) NSString *recommandAttitude;

// 推荐理由
@property(nonatomic, readwrite) BOOL hasRecommandReason;
@property(nonatomic, readwrite, copy) NSString *recommandReason;

// 是否免费
@property(nonatomic, readwrite) BOOL hasIsFree;
@property(nonatomic, readwrite) BOOL isFree;

// 心水价格
@property(nonatomic, readwrite) BOOL hasPrice;
@property(nonatomic, readwrite) int32_t price;

// 已卖数量
@property(nonatomic, readwrite) BOOL hasSellCount;
@property(nonatomic, readwrite) int32_t sellCount;

// 是否已经购买
@property(nonatomic, readwrite) BOOL hasIsBuy;
@property(nonatomic, readwrite) BOOL isBuy;

// 选项
// |betItemsArray| contains |BetItem|
@property(nonatomic, readwrite, strong) NSMutableArray *betItemsArray;

@end

#pragma mark - ExpertWages

typedef GPB_ENUM(ExpertWages_FieldNumber) {
  ExpertWages_FieldNumber_UserInfo = 1,
  ExpertWages_FieldNumber_WagesItemsArray = 2,
  ExpertWages_FieldNumber_IsFocused = 3,
  ExpertWages_FieldNumber_WagesCount = 4,
};

@interface ExpertWages : GPBMessage

//用户信息
@property(nonatomic, readwrite) BOOL hasUserInfo;
@property(nonatomic, readwrite, strong) User *userInfo;

//心水
// |wagesItemsArray| contains |Wages|
@property(nonatomic, readwrite, strong) NSMutableArray *wagesItemsArray;

//是否已经关注 
@property(nonatomic, readwrite) BOOL hasIsFocused;
@property(nonatomic, readwrite) BOOL isFocused;

//心水总数
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int64_t wagesCount;

@end

#pragma mark - HotMatches

typedef GPB_ENUM(HotMatches_FieldNumber) {
  HotMatches_FieldNumber_MatchesArray = 1,
};

@interface HotMatches : GPBMessage

//比赛
// |matchesArray| contains |Match|
@property(nonatomic, readwrite, strong) NSMutableArray *matchesArray;

@end

#pragma mark - MatchWages

typedef GPB_ENUM(MatchWages_FieldNumber) {
  MatchWages_FieldNumber_Match = 1,
  MatchWages_FieldNumber_WagesItemsArray = 2,
  MatchWages_FieldNumber_WagesCount = 3,
  MatchWages_FieldNumber_CommentCount = 4,
};

@interface MatchWages : GPBMessage

//比赛
@property(nonatomic, readwrite) BOOL hasMatch;
@property(nonatomic, readwrite, strong) Match *match;

// 心水列表
// |wagesItemsArray| contains |Wages|
@property(nonatomic, readwrite, strong) NSMutableArray *wagesItemsArray;

//心水数量
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int32_t wagesCount;

//评论数
@property(nonatomic, readwrite) BOOL hasCommentCount;
@property(nonatomic, readwrite) int32_t commentCount;

@end

#pragma mark - MatchComments

typedef GPB_ENUM(MatchComments_FieldNumber) {
  MatchComments_FieldNumber_Match = 1,
  MatchComments_FieldNumber_CommentsArray = 2,
  MatchComments_FieldNumber_WagesCount = 3,
  MatchComments_FieldNumber_CommentCount = 4,
};

//评论
@interface MatchComments : GPBMessage

//比赛
@property(nonatomic, readwrite) BOOL hasMatch;
@property(nonatomic, readwrite, strong) Match *match;

//评论
// |commentsArray| contains |PBMComment|
@property(nonatomic, readwrite, strong) NSMutableArray *commentsArray;

//心水数量
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int32_t wagesCount;

//评论数
@property(nonatomic, readwrite) BOOL hasCommentCount;
@property(nonatomic, readwrite) int32_t commentCount;

@end

#pragma mark - ProfitRanking

typedef GPB_ENUM(ProfitRanking_FieldNumber) {
  ProfitRanking_FieldNumber_ProfitItemsArray = 1,
  ProfitRanking_FieldNumber_LeagueConfigsArray = 2,
};

@interface ProfitRanking : GPBMessage

//对象数组
// |profitItemsArray| contains |ProfitRanking_profitItem|
@property(nonatomic, readwrite, strong) NSMutableArray *profitItemsArray;

// 赛事配置
// |leagueConfigsArray| contains |ProfitRanking_LeagueConfig|
@property(nonatomic, readwrite, strong) NSMutableArray *leagueConfigsArray;

@end

#pragma mark - ProfitRanking_profitItem

typedef GPB_ENUM(ProfitRanking_profitItem_FieldNumber) {
  ProfitRanking_profitItem_FieldNumber_Profit = 1,
  ProfitRanking_profitItem_FieldNumber_UserId = 2,
  ProfitRanking_profitItem_FieldNumber_FansCount = 3,
  ProfitRanking_profitItem_FieldNumber_IsFocused = 4,
  ProfitRanking_profitItem_FieldNumber_UserName = 5,
};

@interface ProfitRanking_profitItem : GPBMessage

//盈利率
@property(nonatomic, readwrite) BOOL hasProfit;
@property(nonatomic, readwrite, copy) NSString *profit;

//用户id
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

//粉丝数
@property(nonatomic, readwrite) BOOL hasFansCount;
@property(nonatomic, readwrite) int32_t fansCount;

//是否已经关注	
@property(nonatomic, readwrite) BOOL hasIsFocused;
@property(nonatomic, readwrite) BOOL isFocused;

//用户名
@property(nonatomic, readwrite) BOOL hasUserName;
@property(nonatomic, readwrite, copy) NSString *userName;

@end

#pragma mark - ProfitRanking_LeagueConfig

typedef GPB_ENUM(ProfitRanking_LeagueConfig_FieldNumber) {
  ProfitRanking_LeagueConfig_FieldNumber_Id_p = 1,
  ProfitRanking_LeagueConfig_FieldNumber_LeagueName = 2,
};

@interface ProfitRanking_LeagueConfig : GPBMessage

@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) int32_t id_p;

// eg : 全部，西甲 ，英超，德甲
@property(nonatomic, readwrite) BOOL hasLeagueName;
@property(nonatomic, readwrite, copy) NSString *leagueName;

@end

#pragma mark - FansRanking

typedef GPB_ENUM(FansRanking_FieldNumber) {
  FansRanking_FieldNumber_FansItemsArray = 1,
};

@interface FansRanking : GPBMessage

//对象数组
// |fansItemsArray| contains |FansRanking_FansItem|
@property(nonatomic, readwrite, strong) NSMutableArray *fansItemsArray;

@end

#pragma mark - FansRanking_FansItem

typedef GPB_ENUM(FansRanking_FansItem_FieldNumber) {
  FansRanking_FansItem_FieldNumber_NewFans = 1,
  FansRanking_FansItem_FieldNumber_UserId = 2,
  FansRanking_FansItem_FieldNumber_UserIcon = 3,
  FansRanking_FansItem_FieldNumber_IsFocused = 4,
  FansRanking_FansItem_FieldNumber_UserName = 5,
};

@interface FansRanking_FansItem : GPBMessage

//新增粉丝
@property(nonatomic, readwrite) BOOL hasNewFans;
@property(nonatomic, readwrite) int32_t newFans;

//用户id
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

//头像
@property(nonatomic, readwrite) BOOL hasUserIcon;
@property(nonatomic, readwrite, copy) NSString *userIcon;

//是否已经关注	
@property(nonatomic, readwrite) BOOL hasIsFocused;
@property(nonatomic, readwrite) BOOL isFocused;

//用户名
@property(nonatomic, readwrite) BOOL hasUserName;
@property(nonatomic, readwrite, copy) NSString *userName;

@end

#pragma mark - CreateWagesInput

typedef GPB_ENUM(CreateWagesInput_FieldNumber) {
  CreateWagesInput_FieldNumber_UserId = 1,
  CreateWagesInput_FieldNumber_GameMatchId = 2,
  CreateWagesInput_FieldNumber_Price = 3,
  CreateWagesInput_FieldNumber_Description_p = 4,
  CreateWagesInput_FieldNumber_DeclareType = 5,
  CreateWagesInput_FieldNumber_Reason = 6,
  CreateWagesInput_FieldNumber_GameTypeId = 7,
};

//创建心水订单入参
@interface CreateWagesInput : GPBMessage

//用户id
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

//比赛id
@property(nonatomic, readwrite) BOOL hasGameMatchId;
@property(nonatomic, readwrite) int64_t gameMatchId;

//方案金额
@property(nonatomic, readwrite) BOOL hasPrice;
@property(nonatomic, readwrite) int32_t price;

//投注内容
@property(nonatomic, readwrite) BOOL hasDescription_p;
@property(nonatomic, readwrite, copy) NSString *description_p;

//类型   1 激进， 2稳健
@property(nonatomic, readwrite) BOOL hasDeclareType;
@property(nonatomic, readwrite) CreateWagesInput_DeclareTypeEnume declareType;

//宣传 
@property(nonatomic, readwrite) BOOL hasReason;
@property(nonatomic, readwrite, copy) NSString *reason;

//类型 
@property(nonatomic, readwrite) BOOL hasGameTypeId;
@property(nonatomic, readwrite) int32_t gameTypeId;

@end

#pragma mark - CreateWagesOuput

typedef GPB_ENUM(CreateWagesOuput_FieldNumber) {
  CreateWagesOuput_FieldNumber_WagesId = 1,
};

//创建心水订单出参
@interface CreateWagesOuput : GPBMessage

//心水id
@property(nonatomic, readwrite) BOOL hasWagesId;
@property(nonatomic, readwrite) int64_t wagesId;

@end

#pragma mark - PayWagesInput

typedef GPB_ENUM(PayWagesInput_FieldNumber) {
  PayWagesInput_FieldNumber_WagesId = 1,
  PayWagesInput_FieldNumber_Password = 2,
};

//购买心水入参
@interface PayWagesInput : GPBMessage

//心水id
@property(nonatomic, readwrite) BOOL hasWagesId;
@property(nonatomic, readwrite) int64_t wagesId;

//支付密码
@property(nonatomic, readwrite) BOOL hasPassword;
@property(nonatomic, readwrite, copy) NSString *password;

@end

#pragma mark - WagesUserInfo

typedef GPB_ENUM(WagesUserInfo_FieldNumber) {
  WagesUserInfo_FieldNumber_Amount = 1,
  WagesUserInfo_FieldNumber_WagesLevel = 2,
  WagesUserInfo_FieldNumber_WagesMaxAmount = 3,
  WagesUserInfo_FieldNumber_IsCanCreateWages = 4,
  WagesUserInfo_FieldNumber_TodayCreateWagesCount = 5,
  WagesUserInfo_FieldNumber_IsOpenBetAccount = 6,
};

//用户心水信息
@interface WagesUserInfo : GPBMessage

//可用余额
@property(nonatomic, readwrite) BOOL hasAmount;
@property(nonatomic, readwrite, copy) NSString *amount;

// 用户等级
@property(nonatomic, readwrite) BOOL hasWagesLevel;
@property(nonatomic, readwrite) int32_t wagesLevel;

//发起心水的最大金额
@property(nonatomic, readwrite) BOOL hasWagesMaxAmount;
@property(nonatomic, readwrite) int32_t wagesMaxAmount;

//是否能发起心水
@property(nonatomic, readwrite) BOOL hasIsCanCreateWages;
@property(nonatomic, readwrite) BOOL isCanCreateWages;

//今日发起心水次数
@property(nonatomic, readwrite) BOOL hasTodayCreateWagesCount;
@property(nonatomic, readwrite) int32_t todayCreateWagesCount;

//是否开通投注账户
@property(nonatomic, readwrite) BOOL hasIsOpenBetAccount;
@property(nonatomic, readwrite) BOOL isOpenBetAccount;

@end

#pragma mark - EditWagesUserInput

typedef GPB_ENUM(EditWagesUserInput_FieldNumber) {
  EditWagesUserInput_FieldNumber_Desription = 1,
};

//修改心水用户信息
@interface EditWagesUserInput : GPBMessage

//用户简介
@property(nonatomic, readwrite) BOOL hasDesription;
@property(nonatomic, readwrite, copy) NSString *desription;

@end

#pragma mark - EditAttention

typedef GPB_ENUM(EditAttention_FieldNumber) {
  EditAttention_FieldNumber_UserId = 1,
};

//设置/取消 关注
@interface EditAttention : GPBMessage

//用户id
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

@end

#pragma mark - Wages

typedef GPB_ENUM(Wages_FieldNumber) {
  Wages_FieldNumber_Id_p = 1,
  Wages_FieldNumber_UserId = 2,
  Wages_FieldNumber_UserName = 3,
  Wages_FieldNumber_UserIcon = 4,
  Wages_FieldNumber_UserLever = 5,
  Wages_FieldNumber_Price = 6,
  Wages_FieldNumber_RecentWinRate = 7,
  Wages_FieldNumber_IsFree = 8,
  Wages_FieldNumber_BuyCount = 9,
  Wages_FieldNumber_IsBuy = 10,
  Wages_FieldNumber_Profit = 11,
  Wages_FieldNumber_BetItemsArray = 12,
};

//心水
@interface Wages : GPBMessage

//心水id
@property(nonatomic, readwrite) BOOL hasId_p;
@property(nonatomic, readwrite) int64_t id_p;

//用户id
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

// 用户名
@property(nonatomic, readwrite) BOOL hasUserName;
@property(nonatomic, readwrite, copy) NSString *userName;

// 用户图标
@property(nonatomic, readwrite) BOOL hasUserIcon;
@property(nonatomic, readwrite, copy) NSString *userIcon;

// 用户等级
@property(nonatomic, readwrite) BOOL hasUserLever;
@property(nonatomic, readwrite) int32_t userLever;

// 心水价格
@property(nonatomic, readwrite) BOOL hasPrice;
@property(nonatomic, readwrite) int32_t price;

// 最近胜率
@property(nonatomic, readwrite) BOOL hasRecentWinRate;
@property(nonatomic, readwrite, copy) NSString *recentWinRate;

// 是否免费
@property(nonatomic, readwrite) BOOL hasIsFree;
@property(nonatomic, readwrite) BOOL isFree;

// 购买人数
@property(nonatomic, readwrite) BOOL hasBuyCount;
@property(nonatomic, readwrite) int32_t buyCount;

//是否已经购买
@property(nonatomic, readwrite) BOOL hasIsBuy;
@property(nonatomic, readwrite) BOOL isBuy;

//预计盈利	
@property(nonatomic, readwrite) BOOL hasProfit;
@property(nonatomic, readwrite, copy) NSString *profit;

//投注比赛
// |betItemsArray| contains |BetItem|
@property(nonatomic, readwrite, strong) NSMutableArray *betItemsArray;

@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_UserName = 1,
  User_FieldNumber_UserLever = 2,
  User_FieldNumber_UserIcon = 3,
  User_FieldNumber_FansCount = 4,
  User_FieldNumber_WinRate = 5,
  User_FieldNumber_RecentWeekWinRate = 6,
  User_FieldNumber_RecentMonthProfit = 7,
  User_FieldNumber_RencentWeekProfit = 8,
  User_FieldNumber_UserTag = 9,
  User_FieldNumber_UserDescrption = 10,
  User_FieldNumber_UserId = 11,
};

//用户
@interface User : GPBMessage

//用户名
@property(nonatomic, readwrite) BOOL hasUserName;
@property(nonatomic, readwrite, copy) NSString *userName;

//等级
@property(nonatomic, readwrite) BOOL hasUserLever;
@property(nonatomic, readwrite) int32_t userLever;

//用户图标
@property(nonatomic, readwrite) BOOL hasUserIcon;
@property(nonatomic, readwrite, copy) NSString *userIcon;

//粉丝数
@property(nonatomic, readwrite) BOOL hasFansCount;
@property(nonatomic, readwrite) int64_t fansCount;

//总胜率
@property(nonatomic, readwrite) BOOL hasWinRate;
@property(nonatomic, readwrite, copy) NSString *winRate;

//近七天胜率
@property(nonatomic, readwrite) BOOL hasRecentWeekWinRate;
@property(nonatomic, readwrite, copy) NSString *recentWeekWinRate;

//最近30天胜率
@property(nonatomic, readwrite) BOOL hasRecentMonthProfit;
@property(nonatomic, readwrite, copy) NSString *recentMonthProfit;

//最近7天盈利
@property(nonatomic, readwrite) BOOL hasRencentWeekProfit;
@property(nonatomic, readwrite, copy) NSString *rencentWeekProfit;

//用户标签
@property(nonatomic, readwrite) BOOL hasUserTag;
@property(nonatomic, readwrite, copy) NSString *userTag;

//用户描述	
@property(nonatomic, readwrite) BOOL hasUserDescrption;
@property(nonatomic, readwrite, copy) NSString *userDescrption;

//用户id	
@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite) int64_t userId;

@end

#pragma mark - BetItem

typedef GPB_ENUM(BetItem_FieldNumber) {
  BetItem_FieldNumber_OrderNumberName = 1,
  BetItem_FieldNumber_StartDate = 2,
  BetItem_FieldNumber_HomeTeamName = 3,
  BetItem_FieldNumber_AwayTemaName = 4,
  BetItem_FieldNumber_Option = 5,
  BetItem_FieldNumber_IsWin = 6,
  BetItem_FieldNumber_Sp = 7,
  BetItem_FieldNumber_Result = 8,
  BetItem_FieldNumber_EndDate = 9,
};

@interface BetItem : GPBMessage

//场次  eg 周三001
@property(nonatomic, readwrite) BOOL hasOrderNumberName;
@property(nonatomic, readwrite, copy) NSString *orderNumberName;

//开始时间 2012-12-12 12:12:12 
@property(nonatomic, readwrite) BOOL hasStartDate;
@property(nonatomic, readwrite, copy) NSString *startDate;

//主队名
@property(nonatomic, readwrite) BOOL hasHomeTeamName;
@property(nonatomic, readwrite, copy) NSString *homeTeamName;

//客队名
@property(nonatomic, readwrite) BOOL hasAwayTemaName;
@property(nonatomic, readwrite, copy) NSString *awayTemaName;

//投注项
@property(nonatomic, readwrite) BOOL hasOption;
@property(nonatomic, readwrite, copy) NSString *option;

//是否中奖
@property(nonatomic, readwrite) BOOL hasIsWin;
@property(nonatomic, readwrite) BOOL isWin;

//赔率
@property(nonatomic, readwrite) BOOL hasSp;
@property(nonatomic, readwrite, copy) NSString *sp;

//比赛结果
@property(nonatomic, readwrite) BOOL hasResult;
@property(nonatomic, readwrite, copy) NSString *result;

//截止时间
@property(nonatomic, readwrite) BOOL hasEndDate;
@property(nonatomic, readwrite, copy) NSString *endDate;

@end

#pragma mark - Match

typedef GPB_ENUM(Match_FieldNumber) {
  Match_FieldNumber_CompetitionName = 1,
  Match_FieldNumber_HomeTeamName = 2,
  Match_FieldNumber_AwayTemaName = 3,
  Match_FieldNumber_EndDate = 4,
  Match_FieldNumber_WagesCount = 5,
  Match_FieldNumber_HomeTeamIcon = 6,
  Match_FieldNumber_AwayTemaIcon = 7,
  Match_FieldNumber_GameTypeId = 8,
  Match_FieldNumber_MatchId = 9,
};

@interface Match : GPBMessage

//联赛名    
@property(nonatomic, readwrite) BOOL hasCompetitionName;
@property(nonatomic, readwrite, copy) NSString *competitionName;

//主队名
@property(nonatomic, readwrite) BOOL hasHomeTeamName;
@property(nonatomic, readwrite, copy) NSString *homeTeamName;

//客队名
@property(nonatomic, readwrite) BOOL hasAwayTemaName;
@property(nonatomic, readwrite, copy) NSString *awayTemaName;

//截止时间
@property(nonatomic, readwrite) BOOL hasEndDate;
@property(nonatomic, readwrite, copy) NSString *endDate;

//心水数量
@property(nonatomic, readwrite) BOOL hasWagesCount;
@property(nonatomic, readwrite) int32_t wagesCount;

// 主队图标
@property(nonatomic, readwrite) BOOL hasHomeTeamIcon;
@property(nonatomic, readwrite, copy) NSString *homeTeamIcon;

// 客队图标
@property(nonatomic, readwrite) BOOL hasAwayTemaIcon;
@property(nonatomic, readwrite, copy) NSString *awayTemaIcon;

//玩法类型
@property(nonatomic, readwrite) BOOL hasGameTypeId;
@property(nonatomic, readwrite) int32_t gameTypeId;

// 比赛id
@property(nonatomic, readwrite) BOOL hasMatchId;
@property(nonatomic, readwrite) int64_t matchId;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
